DROP TABLE IF EXISTS `syy_admins`;
CREATE TABLE `syy_admins` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT, 
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '管理员账号',
  `password` varchar(50) NOT NULL DEFAULT '' COMMENT '密码',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '管理员账号状态 0：禁用 1：开启',
  `created_at` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='管理员表';

INSERT INTO `syy_admins` VALUES (1, 'root', 'e10adc3949ba59abbe56e057f20f883e', 1, 1642750967, 1642750967);

DROP TABLE IF EXISTS `syy_menus`;
CREATE TABLE `syy_menus` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '父级id',
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '菜单名称',
  `url` varchar(300) NOT NULL DEFAULT '' COMMENT '前端路由',
  `icon` varchar(300) NOT NULL DEFAULT '' COMMENT 'icon',
  `is_enabled` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否启用 0：不启用 1：启用',
  `sort` int(11) NOT NULL DEFAULT 0 COMMENT '排序',
  `created_at` int(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='菜单表';

DROP TABLE IF EXISTS `syy_role_has_menus`;
CREATE TABLE `syy_role_has_menus` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `role_id` int(11) NOT NULL DEFAULT '0' COMMENT '角色id',
  `menu_id` int(11) NOT NULL DEFAULT '0' COMMENT '菜单id',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='角色菜单表';

DROP TABLE IF EXISTS `syy_upload_files`;
CREATE TABLE `syy_upload_files` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '文件id',
  `storage` tinyint(1) NOT NULL DEFAULT 0 COMMENT '存储方式 0：本地',
  `file_url` varchar(255) NOT NULL DEFAULT '' COMMENT '存储路径',
  `file_name` varchar(255) NOT NULL DEFAULT '' COMMENT '文件名',
  `file_size` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '文件大小(字节)',
  `file_size_m` varchar(100) NOT NULL DEFAULT '' COMMENT '文件大小(兆)',
  `file_type` varchar(200) NOT NULL DEFAULT '' COMMENT '文件类型',
  `real_name` varchar(255) NOT NULL DEFAULT '' COMMENT '文件真实名',
  `extension` varchar(20) NOT NULL DEFAULT '' COMMENT '文件扩展名',
  `created_at` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COMMENT='文件库记录表';

DROP TABLE IF EXISTS `syy_cases`;
CREATE TABLE `syy_cases` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `admin_id` int(11) NOT NULL DEFAULT 0 COMMENT '管理员id',
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '病员姓名',
  `age` int(11) NOT NULL DEFAULT 0 COMMENT '病员年龄',
  `sex` tinyint(3) NOT NULL DEFAULT 0 COMMENT '性别 0：男 1：女',
  `abstract` varchar(800) NOT NULL DEFAULT '' COMMENT '病史摘要',
  `type_id` int(11) NOT NULL DEFAULT 0 COMMENT '病例类型id',
  `part` varchar(100) NOT NULL DEFAULT '' COMMENT '部位',
  `diagnosis` varchar(300) NOT NULL DEFAULT '' COMMENT '临床诊断',
  `diagnosis_result` varchar(300) NOT NULL DEFAULT '' COMMENT '诊断结果',
  `general_seen` varchar(300) NOT NULL DEFAULT '' COMMENT '大体所见',
  `img_id` int(11) NOT NULL DEFAULT 0 COMMENT '图片id',
  `video_id` int(11) NOT NULL DEFAULT 0 COMMENT '视频id',
  `attachment_id` varchar(20) NOT NULL DEFAULT '' COMMENT '附件id',
  `status` tinyint(3) NOT NULL DEFAULT 1 COMMENT '状态 0：删除 1：正常',
  `created_at` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='病例表';

DROP TABLE IF EXISTS `syy_case_types`;
CREATE TABLE `syy_case_types` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '类型名',
  `created_at` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='病例类型表';

DROP TABLE IF EXISTS `syy_stomach_cas`;
CREATE TABLE `syy_stomach_cas` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `admin_id` int(11) NOT NULL DEFAULT 0 COMMENT '管理员id',
  `img_id` varchar(20) NOT NULL DEFAULT '' COMMENT '图片id',
  `video_id` int(11) NOT NULL DEFAULT 0 COMMENT '视频id',
  `attachment_id` varchar(20) NOT NULL DEFAULT '' COMMENT '附件id',
  `hospital_number` varchar(50) NOT NULL DEFAULT '' COMMENT '住院号',
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '姓名',
  `sex` tinyint(3) NOT NULL DEFAULT 0 COMMENT '1:男 2：女',
  `age` int(11) NOT NULL DEFAULT 0 COMMENT '年龄',
  `national` varchar(50) NOT NULL DEFAULT '' COMMENT '民族',
  `id_card` varchar(50) NOT NULL DEFAULT '' COMMENT '身份证号',
  `mobile` varchar(50) NOT NULL DEFAULT '' COMMENT '患者联系电话',
  `total_money` varchar(50) NOT NULL DEFAULT '' COMMENT '住院总费用',
  `remark` text DEFAULT NULL COMMENT '备注',
  `family_contact` varchar(100) NOT NULL DEFAULT '' COMMENT '家属联系方式',
  `preoperative_chemotherapy` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术前是否化疗 0：否 1：是',
  `preoperative_chemotherapy_laparoscopic_exploration` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术前化疗前是否腹腔镜探查 0：否 1：是',
  `laparoscopic_exploration_time` int(11) NOT NULL DEFAULT 0 COMMENT '腹腔镜探查时间',
  `laparoscopic_exploration_result` tinyint(3) NOT NULL DEFAULT 0 COMMENT '腹腔镜探查结果 1：无腹膜转移 2：有腹膜转移',
  `pci_index` varchar(100) NOT NULL DEFAULT '' COMMENT 'pci 指数',
  `laparoscopic_exploration_cast_off_result` text DEFAULT NULL COMMENT '腹腔镜探查脱落细胞结果',
  `laparoscopic_exploration_biopsy` tinyint(3) NOT NULL DEFAULT 0 COMMENT '腹腔镜探查是否取活检 0：否 1：是',
  `laparoscopic_exploration_biopsy_result` text DEFAULT NULL COMMENT '腹腔镜探查活检结果',
  `laparoscopic_exploration_prognosis` tinyint(3) NOT NULL DEFAULT 0 COMMENT '腹腔镜探查后转归 1：胃肠外科行新辅助化疗 2：肿瘤科姑息治疗',
  `preoperative_chemotherapy_scheme` text DEFAULT NULL COMMENT '术前化疗方案',
  `preoperative_chemotherapy_period` varchar(100) NOT NULL DEFAULT '' COMMENT '术前化疗周期',
  `first_period_chemotherapy_time` int(11) NOT NULL DEFAULT 0 COMMENT '第一周期化疗时间',
  `second_period_chemotherapy_time` int(11) NOT NULL DEFAULT 0 COMMENT '第二周期化疗时间',
  `third_period_chemotherapy_time` int(11) NOT NULL DEFAULT 0 COMMENT '第三周期化疗时间',
  `fourth_period_chemotherapy_time` int(11) NOT NULL DEFAULT 0 COMMENT '第四周期化疗时间',
  `chemotherapy_operative` tinyint(3) NOT NULL DEFAULT 0 COMMENT '化疗后是否手术 0：否 1：是',
  `chemotherapy_adverse_reactions` text DEFAULT NULL COMMENT '化疗期间不良反应',
  `accept_chemotherapy_clinic_evaluate` tinyint(3) NOT NULL DEFAULT 0 COMMENT '接受化疗后临床评价 1：cr 2:pr 3:sd 4:pd',
  `operative_evaluate_effect` text DEFAULT NULL COMMENT '术后病理评效',
  `admission_time` int(11) NOT NULL DEFAULT 0 COMMENT '入院日期时间',
  `operative_time` int(11) NOT NULL DEFAULT 0 COMMENT '手术日期时间',
  `discharge_time` int(11) NOT NULL DEFAULT 0 COMMENT '出院日期时间',
  `total_hospital_days` varchar(50) NOT NULL DEFAULT 0 COMMENT '总住院时间（天）',
  `postoperation_hospital_days` int(11) NOT NULL DEFAULT 0 COMMENT '术后住院时间（天）',
  `ecog_score` varchar(50) NOT NULL DEFAULT '' COMMENT 'ecog 评分',  
  `one_month_loss_of_weight` tinyint(3) NOT NULL DEFAULT 0 COMMENT '1月内体重下降 1：<=5% 2:5-10% 3:>=10%',
  `nrs2002_score` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'nrs2002评分 0: <3 1: >=3',
  `pg_sga_assessment` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'pg-sga评估 1：a 2:b 3:c',
  `nutrition_support_therapy` tinyint(3) NOT NULL DEFAULT 0 COMMENT '营养支持治疗 0：无 1：有',
  `scheme` tinyint(3) NOT NULL DEFAULT 0 COMMENT '方案：1：ten 2:pn+en 3:tpn',
  `days` varchar(100) NOT NULL DEFAULT '' COMMENT '天数（d）',
  `asa_grade` varchar(100) NOT NULL DEFAULT '' COMMENT 'asa分级',
  `main_symptoms` varchar(100) NOT NULL DEFAULT '0' COMMENT '主要症状 0：无 1：腹痛 2：饱胀 3：呕吐 4：呕血 5：便血 6：黑便 7：吞咽困难 8：烧心感 9：厌食 10：乏力 11：体重下降 12：返酸 13：暖气 14：呃逆 15：其他',
  `main_signs` varchar(100) NOT NULL DEFAULT '0' COMMENT '主要体征 0：无 1：腹部压痛 2：腹部包块 3：腹肌抵抗 4：胃型 5：肛检包块/结节 6：振水音 7：左锁骨上淋巴结肿大 8：移动性浊音 9：其他',
  `laparoscopic_operative_record` text DEFAULT NULL COMMENT '腹腔手术史',
  `family_record` text DEFAULT NULL COMMENT '家族史',
  `smoke` tinyint(3) NOT NULL DEFAULT 0 COMMENT '吸烟 0：无 1：有',
  `smoke_year` varchar(50) NOT NULL DEFAULT 0 COMMENT '吸烟（年）',
  `average_smoke_day` varchar(30) NOT NULL DEFAULT '' COMMENT '平均（支/天）',
  `drink` tinyint(3) NOT NULL DEFAULT 0 COMMENT '饮酒 0：无 1：有',
  `drink_year` varchar(30) NOT NULL DEFAULT '' COMMENT '饮酒年',
  `average_drink_day` varchar(30) NOT NULL DEFAULT '' COMMENT '平均（g/天）',
  `height` varchar(30) NOT NULL DEFAULT '' COMMENT '身高cm',
  `weight` varchar(30) NOT NULL DEFAULT '' COMMENT '体重kg',
  `bmi` text DEFAULT NULL COMMENT 'bmi',
  `hp` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'hp 0:阴性 1：阳性',
  `ecg` tinyint(3) NOT NULL DEFAULT 0 COMMENT '心电图 0：无特殊 1：特殊异常',
  `preoperative_lung_function` text DEFAULT NULL COMMENT '术前肺功能fev1/fvc(%)',
  `preoperative_ct` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术前ＣＴ 1＝Tx ；2＝T1a-M；T1b-SM：3＝T2-MP：4＝T3-SS；5＝T4a-SE：6＝T4b-SI：)',
  `n_aging` tinyint(3) NOT NULL DEFAULT 0 COMMENT '(Ｎ分期　1=N0/区域淋巴结无转移；　2=N1/1-2个区域淋巴结转移；3=N2/3-6个区域淋巴结转移；4=N3/7个以上区域淋巴结转移；5=Nx/区域淋巴结无法评估)',
  `preoperative_ct_check_m_aging` text DEFAULT NULL COMMENT '术前ＣＴ检查Ｍ分期　０＝  Ｍ０    1＝   Ｍ１　具 体部位)',
  `preoperative_aging` text DEFAULT NULL COMMENT '术前分期ctnm',
  `preoperative_complications_check_exception` varchar(500) NOT NULL DEFAULT '' COMMENT '术前合并症/术前检查异常',
  `preoperative_complications` varchar(100) NOT NULL DEFAULT '0' COMMENT '术前合并症　　１＝呼吸系统（COPD，哮喘，肺心病）；２＝循环系统（高血压，心功能不全（NYHA Ⅲ或Ⅳ)，陈旧性心肌梗塞）；３＝消化系统（肝炎，肝硬化，门脉高压，消化道溃疡，炎性肠病）；４＝内分泌（甲亢，糖尿病）；５＝泌尿系统（慢性肾炎，肾功能不全）；６＝神经系统（陈旧性脑梗塞）７＝患有其他恶性疾病：疾病名称；８＝免疫疾病后长期服用免疫抑制剂；９＝凝血机制异常或长期使用抗凝药物；１０＝其他：具体情况',
  `preoperative_chest_ct` text DEFAULT NULL COMMENT '术前胸部CT       0=正常，1=慢支，2=肺气肿，3=肺部感染，4=胸水，5=心脏长大，6=肺部占位，7=肿瘤肺部转移：具体部位',
  `ultrasound_gastroscope_tnm` text DEFAULT NULL COMMENT '超声胃镜tnm', 
  `ultrasound_imaging_tnm` text DEFAULT NULL COMMENT '超声造影tnm',
  `laparoscopic_fat_volumne` text DEFAULT NULL COMMENT '腹腔内脂肪容积',
  `napes_fat_volumne` text DEFAULT NULL COMMENT '腹壁脂肪容积',
  `her_2` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'her-2 0:阴性 1：阳性',
  `rbc` text DEFAULT NULL COMMENT 'rbc',
  `hemoglobin` varchar(100) NOT NULL DEFAULT '' COMMENT '血红蛋白（g/l）',
  `gpt` varchar(100) NOT NULL DEFAULT '' COMMENT '谷丙转氨酶alt u/l',
  `got` varchar(100) NOT NULL DEFAULT '' COMMENT '谷草转氨酶ast u/l',
  `tbil` varchar(100) NOT NULL DEFAULT '' COMMENT '总胆红素tbil mmol/l',
  `tp` varchar(100) NOT NULL DEFAULT '' COMMENT '总蛋白tp g/l',
  `alb` varchar(100) NOT NULL DEFAULT '' COMMENT '白蛋白 alb g/l',
  `palb` varchar(100) NOT NULL DEFAULT '' COMMENT '前白蛋白 palb g/l',
  `glu` text DEFAULT NULL COMMENT 'glu',
  `tg` text DEFAULT NULL COMMENT 'tg',
  `crea` text DEFAULT NULL COMMENT 'crea',
  `d_dimer` text DEFAULT NULL COMMENT 'd-dimer',
  `blood_type` tinyint(3) NOT NULL DEFAULT 0 COMMENT '血型 1：a 2:b 3:o 4:ab',
  `preoperative_afp` text DEFAULT NULL COMMENT '术前afp',
  `preoperative_cea` text DEFAULT NULL COMMENT '术前cea',
  `preoperative_ca19_9` text DEFAULT NULL COMMENT '术前ca19-9',
  `preoperative_ca125` text DEFAULT NULL COMMENT '术前ca125',
  `preoperative_ca15_3` text DEFAULT NULL COMMENT '术前ca15-3',
  `preoperative_ca72_4` text DEFAULT NULL COMMENT '术前ca72-4',
  `gas_17` text DEFAULT NULL COMMENT '胃泌素-17',
  `pepsinogen_1` text DEFAULT NULL COMMENT '胃蛋白酶原1',
  `pepsinogen_2` text DEFAULT NULL COMMENT '胃蛋白酶原2',
  `pepsinogen_1_divide_pepsinogen_2` text DEFAULT NULL COMMENT '1/2比值',
  `preoperative_ll_6` text DEFAULT NULL COMMENT '术前ll-6',
  `vitb12` text DEFAULT NULL COMMENT 'vitb12',
  `folate` text DEFAULT NULL COMMENT '叶酸',
  `evb_ca_lga` text DEFAULT NULL COMMENT 'evb-ca-lga',
  `ebv_ea_lgg` text DEFAULT NULL COMMENT 'ebv-ea-lgg',
  `pg_1_divide_pg_2` text DEFAULT NULL COMMENT 'pg-1/pg-2比值',
  `stool_ob` tinyint(3) NOT NULL DEFAULT 0 COMMENT '大便隐血 0:阴 1：阳',
  `postoperative_afp` text DEFAULT NULL COMMENT '术后afp',
  `postoperative_cea` text DEFAULT NULL COMMENT '术后cea',
  `postoperative_ca19_9` text DEFAULT NULL COMMENT '术后ca19-9',
  `postoperative_ca72_4` text DEFAULT NULL COMMENT '术后ca72-4',
  `postoperative_ca125` text DEFAULT NULL COMMENT '术后125',
  `postoperative_ca15_3` text DEFAULT NULL COMMENT '术后ca15-3',
  `postoperative_rbc` text DEFAULT NULL COMMENT '术后rbc',
  `postoperative_hemoglobin` text DEFAULT NULL COMMENT '术后血红蛋白',
  `postoperative_gpt` varchar(100) NOT NULL DEFAULT '' COMMENT '术后谷丙转氨酶alt u/l',
  `postoperative_got` varchar(100) NOT NULL DEFAULT '' COMMENT '术后谷草转氨酶ast u/l',
  `postoperative_tbil` varchar(100) NOT NULL DEFAULT '' COMMENT '术后总胆红素tbil mmol/l',
  `postoperative_tp` varchar(100) NOT NULL DEFAULT '' COMMENT '术后总蛋白tp g/l',
  `postoperative_alb` varchar(100) NOT NULL DEFAULT '' COMMENT '术后白蛋白 alb g/l',
  `postoperative_glu` varchar(100) NOT NULL DEFAULT '' COMMENT '术后glu',
  `postoperative_tg` varchar(100) NOT NULL DEFAULT '' COMMENT '术后tg',
  `postoperative_crea` varchar(100) NOT NULL DEFAULT '' COMMENT '术后crea',
  `d_d2` text DEFAULT NULL COMMENT 'd-d2',
  `amylase_in_puncture_fluid` text DEFAULT NULL COMMENT '穿刺液淀粉酶',
  `surgical_intervention` tinyint(3) NOT NULL DEFAULT 0 COMMENT '外科干预方式(0=未手术，1=根治性切除，2=姑息性切除，3=姑息性胃空肠吻合，4=探查)',
  `surgeon` varchar(100) NOT NULL DEFAULT '' COMMENT '术者',
  `road_way` tinyint(3) NOT NULL DEFAULT 0 COMMENT '入路方式（0=原位；1=拖出；2=后入路原位-3=开腹）',
  `road` tinyint(3) NOT NULL DEFAULT 0 COMMENT '入路(1=开腹，2=腹腔镜，3=胸腹联合，4=开腹+食管膈肌裂孔，5=腹腔镜+食管膈肌裂孔)',
  `laparoscopic_exploration_laparoscopy` text DEFAULT NULL COMMENT '腹腔镜探查后中转开腹原因 具体',
  `removal_way` tinyint(3) NOT NULL DEFAULT 0 COMMENT '切除方式(1=DG，2=TG，3=PG,4=局部切除)',
  `lymphadenectomy` tinyint(3) NOT NULL DEFAULT 0 COMMENT '淋巴结清扫(1=D1，2=D2，3=D2+，4=D2+PAND，5=D1+)',
  `rebuild` tinyint(3) NOT NULL DEFAULT 0 COMMENT '重建(1=Billroth-1，2=Billroth-2，3=Roux-en-Y，4=EGA，5=JPI；6=Braun)',
  `omental_sac_resection` tinyint(3) NOT NULL DEFAULT 0 COMMENT '网膜囊切除（0=未切除；1=不完全切除；2=网膜囊切除）',
  `omental_sac_resection_minutes`varchar(100) NOT NULL DEFAULT 0 COMMENT '网膜囊切除时间（分）',
  `splenic_hilar_lymph_node_clear_minutes` varchar(100) NOT NULL DEFAULT 0 COMMENT '脾门淋巴结清扫时间（分）',
  `simultaneous_organoectomy_resection` varchar(100) NOT NULL DEFAULT '0' COMMENT '联合脏器切除(0=无，1=脾脏，2=左肝外叶，3=胰头，4=横结肠，5=胆囊，6=卵巢，7=小肠)',
  `intraoperative_organ_injury_occurred` varchar(100) NOT NULL DEFAULT '0' COMMENT '术中并发器官损伤(0=无，1=血管，2=脾脏，3=胰，4=横结肠，5=胆囊，6=肝脏)',
  `intraoperative_organ_injury_occurred_handle` text DEFAULT NULL COMMENT '术中并发症-出血处理',
  `intraoperative_complications_bleeding_site` text DEFAULT NULL COMMENT '术中并发症-出血部位',
  `operation_minutes` varchar(100) NOT NULL DEFAULT '' COMMENT '手术时间（分）',
  `intraoperative_blood_loss_was_estimated` varchar(100) NOT NULL DEFAULT '' COMMENT '术中估计出血量ml',
  `perioperative_blood_transfusion` tinyint(3) NOT NULL DEFAULT 0 COMMENT '围术期输血(0=未输血；1=术前；2=术中；3=术后；RBC，FFP，ALB。eg: 1-RBC 2U, 3-FFP 200ml)',
  `adverse_reactions_of_perioperative_blood_transfusion` tinyint(3) NOT NULL DEFAULT 0 COMMENT '围术期输血不良反应(0=无；1=发热；2=过敏；3=溶血；4=其它)',
  `perioperative_transfusion_unit` varchar(100) NOT NULL DEFAULT '' COMMENT '围术期输血单位',
  `chemotherapy_during_operation` varchar(100) NOT NULL DEFAULT '' COMMENT '术中化疗(0=无; 1=IOC:具体)',
  `intraoperative_carbon_nanotracers` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术中纳米碳示踪(0=否; 1=是)',
  `intraoperative_arterial_infusion_chemotherapy` text DEFAULT NULL COMMENT '术中动脉灌注化疗',
  `intraoperative_results_of_special_freezing` text DEFAULT NULL COMMENT '术中特殊冰冻结果(如网膜结节系低分化腺癌)',
  `ascites` tinyint(3) NOT NULL DEFAULT 0 COMMENT '腹水(0:无; 1:少量；2：中量；3：大量)',
  `cancer_cell` tinyint(3) NOT NULL DEFAULT 0 COMMENT ' 0=CY0:腹腔脱落癌细胞检查,未见癌细胞;     1=CY1: 找到癌细胞;    X=CYX:未做腹腔脱落癌细胞检查。',
  `peritoneal_metastasis` tinyint(3) NOT NULL DEFAULT 0 COMMENT '腹膜转移（0=P0 无腹膜扩散）；1=P1 癌灶附近腹膜，大网膜及横结肠系膜种植）；2=P2 横结肠下及膈肌腹膜少数癌灶）；3=P3 远处腹膜多数癌灶种植）；4=Px 腹膜转移无法判断）',
  `hepatic_metastases` text DEFAULT NULL COMMENT '肝转移(0:无; 1:具体)',
  `single_hepatic_metastases` tinyint(3) NOT NULL DEFAULT 0 COMMENT '单个肝转移（１＝左叶；２＝右叶）',
  `more_hepatic_metastases` tinyint(3) NOT NULL DEFAULT 0 COMMENT '多个肝转移（１＝左叶；２＝右叶；3=左右叶均有）',
  `lymph_nodes_were_enlarged_in_16` text DEFAULT NULL COMMENT '腹膜后、肠系膜根部、16组淋巴结肿大',
  `number_of_tumor_lesions` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肿瘤病灶个数 1=单病灶；2=双病灶；3=三病灶及更多',
  `longitudinal_position_of_a_single_lesion` tinyint(3) NOT NULL DEFAULT 0 COMMENT '单病灶肿瘤纵向部位(1=胃上部U，2=胃体M，3=胃下部L，4=U+食管受累E，5=UM/MU，6=LM/ML，7=L+十二指肠受累D，8=LMU/MLU/MUL/UML)',
  `aeg` tinyint(3) NOT NULL DEFAULT 0 COMMENT '食管胃结合部腺癌  0=否，1=siewert-I型，2=siewert-II型，3=siewert-III型',
  `peridiameter_of_the_tumor` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肿瘤周径部位(1=小弯，2=大弯，3=前壁，4=后壁，5=全周)',
  `greatest_tumor_diameter` varchar(100) NOT NULL DEFAULT '' COMMENT '肿瘤最大径（如果为双病灶肿瘤描述主体病灶）(cm)',
  `intraoperative_depth_of_tumor_invasion` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术中肿瘤浸润深度 (1=原位癌，2=粘膜层，3=粘膜下层，4=浅肌层，5=深肌层，6=浆膜下层，7=浆膜层，8=临近器官受侵)',
  `cancer` tinyint(3) NOT NULL DEFAULT 0 COMMENT '(1=早癌，2=Borr-1，3=Borr-2，4=Borr-3，5=Borr-4)',
  `early_cancer_t1` tinyint(3) NOT NULL DEFAULT 0 COMMENT '早癌(T1)大体分型1=0-I 隆起型，2=0-IIa 表浅隆起型，3=0-IIb 平坦型，4=0-IIc 表浅凹陷性，5=III 凹陷型，6=混合型(按病变面积记录)', 
  `radical_degrees` tinyint(3) NOT NULL DEFAULT 0 COMMENT '根治度  1=R0；2=R1；3=R2',
  `distance_between_the_proximal_margin_and_the_tumor` varchar(100) NOT NULL DEFAULT '' COMMENT '近切缘距肿瘤距离cm',
  `distance_of_distal_margin_to_tumor` varchar(100) NOT NULL DEFAULT '' COMMENT '远切缘距肿瘤距离cm',
  `dual_foci_neoplasms_foci_1_nature` tinyint(3) NOT NULL DEFAULT 0 COMMENT '双病灶肿瘤 病灶-1：性质(1=AC=腺癌，2=GIST=间质肿瘤，3=LYM=淋巴瘤，4=NC=神经内分泌癌，5=OTHER=其它特殊类型)',
  `dual_foci_neoplasms_foci_2_nature` tinyint(3) NOT NULL DEFAULT 0 COMMENT '双病灶肿瘤 病灶-2：性质(1=AC=腺癌，2=GIST=间质肿瘤，3=LYM=淋巴瘤，4=NC=神经内分泌癌，5=OTHER=其它特殊类型)',
  `double_focal_tumor_site` tinyint(3) NOT NULL DEFAULT 0 COMMENT '双病灶肿瘤主病灶部位    1=病灶-1，    2=病灶-2',
  `bifoci_tumor_site_foci_1` tinyint(3) NOT NULL DEFAULT 0 COMMENT '双病灶肿瘤部位 病灶-1：(1=胃上部U，2=胃体M，3=胃下部L，4=U+食管受累E，5=UM/MU，6=LM/ML，7=L+十二指肠受累D，8=LMU/MLU/MUL/UML)，9=其他',
  `bifoci_tumor_site_foci_2` tinyint(3) NOT NULL DEFAULT 0 COMMENT '双病灶肿瘤部位 病灶-2：(1=胃上部U，2=胃体M，3=胃下部L，4=U+食管受累E，5=UM/MU，6=LM/ML，7=L+十二指肠受累D，8=LMU/MLU/MUL/UML)，9=其他',
  `three_or_more_lesions_and_multiple_lesions` text DEFAULT NULL COMMENT '三病灶以上多病灶肿瘤具体描述',
  `single_focal_tumor_pathology` tinyint(3) NOT NULL DEFAULT 0 COMMENT '单病灶肿瘤病理类型(1=AC=腺癌，2=GIST=间质肿瘤，3=LYM=淋巴瘤，4=NC=神经内分泌癌，5=OTHER=其它特殊类型)',
  `cell_type` tinyint(3) NOT NULL DEFAULT 0 COMMENT '细胞类型（1=乳头腺癌，2=管状腺癌，3=腺癌，4=印戒细胞癌，5=粘液细胞癌，6=类癌，7=内分泌细胞癌，8=其它，具体描述）',
  `adenocarcinoma_of_differentiation` tinyint(3) NOT NULL DEFAULT 0 COMMENT '腺癌分化程度1=Gx-无法评估；2=G1-高分化；3=G2-中分化；4=G3-低分化；5=G4-未分化；6=印戒；7=粘液腺癌',
  `lauren_type` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'lauren分型      1=肠型；2=弥漫型;3=混合型',
  `level_of_tumor` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肿瘤级别(淋巴瘤-侵袭度）1=低侵袭度；2=高侵袭度',
  `lymphoma_tnm_aging` text DEFAULT NULL COMMENT '淋巴瘤：TNM分期',
  `detection_of_frozen_cutting_edge_disease` tinyint(3) NOT NULL DEFAULT 0 COMMENT '冰冻切缘病检（0:阴性; 1：食管断端阳性；2：十二指肠断端阳性；3：胃大弯阳性；4：胃小弯阳性)',
  `resect_the_inspection_margin_again` tinyint(3) NOT NULL DEFAULT 0 COMMENT '再次切除送检切缘  0=无需再次送检，1：食管断端阴性；2：十二指肠断端阴性；3：胃大弯阴性；4：胃小弯阴性',
  `greater_omentum_margin_was_examined` tinyint(3) NOT NULL DEFAULT 0 COMMENT '大网膜边缘送检：0=阴性；1=阳性',
  `examination_of_lesser_omentum_margin` tinyint(3) NOT NULL DEFAULT 0 COMMENT '小网膜边缘送检：0=阴性；1=阳性',
  `ft_aging` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'fT分期 (1=原位癌，2=粘膜层，3=粘膜下层，4=浅肌层，5=深肌层，6=浆膜下层，7=浆膜层，8=临近器官受侵)',
  `adjacent_structures_are_infiltrated_directly` varchar(100) NOT NULL DEFAULT '0' COMMENT '邻近结构直接浸润(0=无，1=脾脏，2=肝脏，3=胰腺，4=横结肠，5=胆囊，6=胆道，7=膈肌，8=腹后壁，9=腹前壁)',
  `fn_aging` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'fN-分期（0=N0，1=N1，2=N2,3=N3a，4=N3b，X=不详）',
  `fm_aging` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'fM分期（0=M0，1=M1）',
  `m1_aging` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'M1分期  1=淋巴结(LYM)，2=皮肤(SKI)，3=肺(PUL)，4=骨髓(MAR)，5=骨(OSS)，6=胸腔(PLE)，7=脑(BRA)，8=脑膜(MEN)，9=肾上腺(ADR)，10=后腹膜(RET)，11=卵巢(OVA)，12=肝(H), 13=腹腔脱落细胞(CY), 14=腹膜(P),15=其他(OTH)',
  `ftnm_jgca` text DEFAULT NULL COMMENT 'fTNM-JGCA',
  `ftnm` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'fTNM-(1=IA，2=IB，3=IIA，4=IIB，5=IIIA，6=IIIB，7=IIIC，8=IV，X=不详)',
  `her2` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'HER2(0=0;1=1+;2=2+;3=3+;4=4+)',
  `lymphadenectomy_total` varchar(100) NOT NULL DEFAULT 0 COMMENT '淋巴结清扫总数',
  `lymph_node` varchar(100) NOT NULL DEFAULT '' COMMENT '淋巴结+', 
  `regional_lymph_nodes_cancer_nodules` varchar(100) NOT NULL DEFAULT '' COMMENT '区域淋巴结有无癌结节；0=无，1=组/个数；组/个数',
  `no1_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no.1_plus',
  `no1` varchar(100) NOT NULL DEFAULT '' COMMENT 'no1',
  `no2_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no2_plus',
  `no2` varchar(100) NOT NULL DEFAULT '' COMMENT 'no2',
  `no3_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no3_plus',
  `no3` varchar(100) NOT NULL DEFAULT '' COMMENT 'no3',
  `no3a_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no3a_plus',
  `no3a` varchar(100) NOT NULL DEFAULT '' COMMENT 'no3a',
  `no3b_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no3b_plus',
  `no3b` varchar(100) NOT NULL DEFAULT '' COMMENT 'no3b',
  `no4d_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no4d_plus',
  `no4d` varchar(100) NOT NULL DEFAULT '' COMMENT 'no4d',
  `no4sb_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no4sb_plus',
  `no4sb` varchar(100) NOT NULL DEFAULT '' COMMENT 'no4sb',
  `no4sa_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no4sa_plus',
  `no4sa` varchar(100) NOT NULL DEFAULT '' COMMENT 'no4sa',
  `no5_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no5_plus',
  `no5` varchar(100) NOT NULL DEFAULT '' COMMENT 'no5',
  `no6_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no6_plus',
  `no6` varchar(100) NOT NULL DEFAULT '' COMMENT 'no6',
  `no6a_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no6a_plus',
  `no6a` varchar(100) NOT NULL DEFAULT '' COMMENT 'no6a',
  `no6b_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no6b_plus',
  `no6b` varchar(100) NOT NULL DEFAULT '' COMMENT 'no6b',
  `no6c_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no6c_plus',
  `no6c` varchar(100) NOT NULL DEFAULT '' COMMENT 'no6c',
  `no7_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no7_plus',
  `no7` varchar(100) NOT NULL DEFAULT '' COMMENT 'no7',
  `no8a_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no8a_plus',
  `no8a` varchar(100) NOT NULL DEFAULT '' COMMENT 'no8a',
  `no8p_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no8p_plus',
  `no8p` varchar(100) NOT NULL DEFAULT '' COMMENT 'no8p',
  `no9_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no9_plus',
  `no9` varchar(100) NOT NULL DEFAULT '' COMMENT 'no9',
  `no10_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no10_plus',
  `no10` varchar(100) NOT NULL DEFAULT '' COMMENT 'no10',
  `no10p_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no10p_plus',
  `no10p` varchar(100) NOT NULL DEFAULT '' COMMENT 'no10p',
  `no11p_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no11p_plus',
  `no11p` varchar(100) NOT NULL DEFAULT '' COMMENT 'no11p',
  `no11p_back_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no11p_back_plus',
  `no11p_back` varchar(100) NOT NULL DEFAULT '' COMMENT 'no11p_back',
  `no11d_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no11d_plus',
  `no11d` varchar(100) NOT NULL DEFAULT '' COMMENT 'no11d',
  `no12a_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no12a_plus',
  `no12a` varchar(100) NOT NULL DEFAULT '' COMMENT 'no12a',
  `no12p_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no12p_plus',
  `no12p` varchar(100) NOT NULL DEFAULT '' COMMENT 'no12p',
  `no12b_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no12b_plus',
  `no12b` varchar(100) NOT NULL DEFAULT '' COMMENT 'no12b',
  `no12h_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no12h_plus',
  `no12h` varchar(100) NOT NULL DEFAULT '' COMMENT 'no12h',
  `no13_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no13_plus',
  `no13` varchar(100) NOT NULL DEFAULT '' COMMENT 'no13',
  `no14v_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no14v_plus',
  `no14v` varchar(100) NOT NULL DEFAULT '' COMMENT 'no14v',
  `no15_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no15_plus',
  `no15` varchar(100) NOT NULL DEFAULT '' COMMENT 'no15',
  `no16a1_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no16a1_plus',
  `no16a1` varchar(100) NOT NULL DEFAULT '' COMMENT 'no16a1',
  `no16a2_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no16a2_plus',
  `no16a2` varchar(100) NOT NULL DEFAULT '' COMMENT 'no16a2',
  `no16b1_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no16b1_plus',
  `no16b1` varchar(100) NOT NULL DEFAULT '' COMMENT 'no16b1',
  `no16b2_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no16b2_plus',
  `no16b2` varchar(100) NOT NULL DEFAULT '' COMMENT 'no16b2',
  `no17_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no17_plus',
  `no17` varchar(100) NOT NULL DEFAULT '' COMMENT 'no17',
  `no18_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no18_plus',
  `no18` varchar(100) NOT NULL DEFAULT '' COMMENT 'no18',
  `no19_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no19_plus',
  `no19` varchar(100) NOT NULL DEFAULT '' COMMENT 'no19',
  `no20_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no20_plus',
  `no20` varchar(100) NOT NULL DEFAULT '' COMMENT 'no20',
  `no110_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no110_plus',
  `no110` varchar(100) NOT NULL DEFAULT '' COMMENT 'no110',
  `no111_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no111_plus',
  `no111` varchar(100) NOT NULL DEFAULT '' COMMENT 'no111',
  `no112_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no112_plus',
  `no112` varchar(100) NOT NULL DEFAULT '' COMMENT 'no112',
  `small_mesenteric_ln_plus` text DEFAULT NULL COMMENT '小肠系膜ln_plus',
  `small_mesenteric_ln` text DEFAULT NULL COMMENT '小肠系膜ln',
  `special_lymph_node` text DEFAULT NULL COMMENT '特殊淋巴结（具体描述：部位，阳性数目/清扫数目）',
  `vascular_involvement` tinyint(3) NOT NULL DEFAULT 0 COMMENT '血管受累(0=阴性；1=阳性；X=未报道)',
  `lymphatic_involvement` tinyint(3) NOT NULL DEFAULT 0 COMMENT '淋巴管受累(0=阴性；1=阳性；X=未报道)',
  `neurologic_involvement` tinyint(3) NOT NULL DEFAULT 0 COMMENT '神经受累(0=阴性；1=阳性；X=未报道)',
  `fat_examination_reveals_cancerous_nodules` tinyint(3) NOT NULL DEFAULT 0 COMMENT '脂肪查见癌结节(0=阴性；1=阳性-具体；X=未报道)',
  `vascular_tumor_emboli` tinyint(3) NOT NULL DEFAULT 0 COMMENT '脉管癌栓(0=阴性；1=阳性；X=未报道)',
  `hepatoduodenal_ligament_anterior_peritoneum` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肝十二指肠韧带腹膜前叶(0=阴性；1=阳性；X=未报道)',
  `pancreas_capsule` tinyint(3) NOT NULL DEFAULT 0 COMMENT '胰腺被膜(0=阴性；1=阳性；X=未报道)',
  `anterior_lobe_of_transverse_mesentery` tinyint(3) NOT NULL DEFAULT 0 COMMENT '横结肠系膜前叶(0=阴性；1=阳性；X=未报道)',
  `stage_show` text DEFAULT NULL COMMENT '分期说明（术前MDCT，术中特殊发现，术后病理特殊信息）',
  `pathology_num` varchar(100) NOT NULL DEFAULT '' COMMENT '病理号（另自行保存病理报告副本pdf文档，以病理号命名）',
  `perioperative_nutritional_support` text DEFAULT NULL COMMENT '围术期营养支持(包括具体方案，持续时间，不良反应)',
  `perioperative_antibiotics` text DEFAULT NULL COMMENT '围术期抗生素',
  `postoperative_prophylactic_antibiotic` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术后预防抗生素(1=常规用法，2=短程用法)',
  `perioperative_acid_suppressor` text DEFAULT NULL COMMENT '围术期抑酸剂',
  `perioperative_mucosal_protectant` text DEFAULT NULL COMMENT '围术期黏膜保护剂',
  `perioperative_hemostatic_agent` text DEFAULT NULL COMMENT '围术期止血药(0:无; 1:具体)',
  `perioperative_somatostatin` tinyint(3) NOT NULL DEFAULT 0 COMMENT '围术期生长抑素(0=无，1=有)',
  `perioperative_analgesics` text DEFAULT NULL COMMENT '围术期镇痛药',
  `perioperative_intensive_care` text DEFAULT NULL COMMENT '围术期重症监护',
  `other_special_treatments_during_perioperative_period` text DEFAULT NULL COMMENT '围术期其他特殊处理',
  `whether_to_install_a_gastric_tube` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否安置胃管（1，是；2，否）',
  `set_time` int(11) NOT NULL DEFAULT 0 COMMENT '安置时间（1，术前；2、术中；3，术后）',
  `extraction_date_of_gastric_tube_time` int(11) NOT NULL DEFAULT 0 COMMENT '胃管拔除日(POD)',
  `average_daily_gastric_fluid_volume` varchar(100) NOT NULL DEFAULT '' COMMENT '每日平均胃液量(ml)',
  `cause_of_gastric_tube_replacement` text DEFAULT NULL COMMENT '再次安置胃管原因：具体描述',
  `catheter_removal_time` int(11) NOT NULL DEFAULT 0 COMMENT '尿管拔除时间(POH)',
  `abdominal_drainage_tube_removal_date_time` int(11) NOT NULL DEFAULT 0 COMMENT '腹腔引流管拔除日(POD)',
  `average_daily_volume_of_abdominal_drainage_fluid` varchar(100) NOT NULL DEFAULT '' COMMENT '每日平均腹腔引流液量(ml)',
  `anal_exhaust_day_time` int(11) NOT NULL DEFAULT 0 COMMENT '肛门排气日(h)', 
  `start_an_out_of_bed_day_time` int(11) NOT NULL DEFAULT 0 COMMENT '开始下床活动日(POH)',
  `start_a_fluid_day_time` int(11) NOT NULL DEFAULT 0 COMMENT '开始进食流质日(POH)',
  `highest_temperature` varchar(100) NOT NULL DEFAULT '' COMMENT '最高体温(℃)',
  `postoperative_temperature_greater_than_38_days` varchar(100) NOT NULL DEFAULT '' COMMENT '术后体温>38℃天数(day)',
  `perioperative_complications` varchar(100) NOT NULL DEFAULT '0' COMMENT '围术期手术并发症(0=无；1=十二指肠残端瘘，2=吻合口瘘，3=胰瘘/胰腺炎，4=肠瘘，5=胆瘘，6=淋巴乳糜瘘，7=腹腔内出血，8=消化道出血，9=麻痹性肠梗阻，10=机械性梗阻，11=胃无张力，12=切口感染/切口裂开，13=腹腔感染/腹腔脓肿/腹腔局限性积液，14=血管损伤，15=临近器官损伤，16=腹腔镜相关并发症)',
  `management_of_perioperative_complications` text DEFAULT NULL COMMENT '围术期手术并发症处理方式',
  `nonoperative_complication` text DEFAULT NULL COMMENT '非手术并发症',
  `perioperative_management_of_nonoperative_complications` text DEFAULT NULL COMMENT '围术期非手术并发症处理方式',
  `outcome` tinyint(3) NOT NULL DEFAULT 0 COMMENT '转归(1=无并发症出院，2=并发症治愈出院，3=自动出院，4=死亡)',
  `inputting_medical_records` varchar(100) NOT NULL DEFAULT '' COMMENT '病历信息录入者',
  `is_the_record_entry_complete` text DEFAULT NULL COMMENT '病历录入是否完整',
  `medical_records_information_checker` varchar(100) NOT NULL DEFAULT '' COMMENT '病历信息核查者',
  `created_at` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='胃ca表';

DROP TABLE IF EXISTS `syy_stomach_follow_ups`;
CREATE TABLE `syy_stomach_follow_ups` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `stomach_ca_id` int(11) NOT NULL DEFAULT 0 COMMENT '胃ca id',
  `dead_time` int(11) NOT NULL DEFAULT 0 COMMENT '死亡日期时间(月)',
  `survival_month` varchar(100) NOT NULL DEFAULT '' COMMENT '生存月份',
  `followed_up_after_operation_date_time` int(11) NOT NULL DEFAULT 0 COMMENT '术后随访日期时间',
  `results_were_followed_up_after_operation` varchar(500) NOT NULL DEFAULT '' COMMENT '随访结局，1=无瘤生存；2=带瘤生存；3=肿瘤原因死亡；4=其他原因死亡；5=失访，原因 ',
  `long_term_complications_and_management_methods` text DEFAULT NULL COMMENT '远期并发症及处理方式',
  `whether_new_hair_gallbladder_stone` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否新发胆囊结石（0=否；1=是，2=既往合并胆囊结石）',
  `gallstone_discovery_time` int(11) NOT NULL DEFAULT 0 COMMENT '胆囊结石发现时间（年-月-日）',
  `treatment_of_gallstones` tinyint(3) NOT NULL DEFAULT 0 COMMENT '胆囊结石处理方式（1=保守，2=手术）',
  `local_recurrence_time` int(11) NOT NULL DEFAULT 0 COMMENT '局部复发时间',
  `distant_transfer_time` int(11) NOT NULL DEFAULT 0 COMMENT '远处转移时间',
  `distant_metastatic_site` varchar(300) NOT NULL DEFAULT '' COMMENT '远处转移部位（非肿瘤死亡原因）',
  `whether_chemotherapy` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否化疗 0=无；1=有；2=新辅助',
  `chemotherapy_way` tinyint(3) NOT NULL DEFAULT 0 COMMENT '化疗途径  1=口服；2=静脉',
  `chemotherapy_regimens` text DEFAULT NULL COMMENT '化疗方案',
  `chemotherapy_regimen_rate` varchar(100) NOT NULL DEFAULT '' COMMENT '化疗疗程/次',
  `chemotherapy_month` varchar(100) NOT NULL DEFAULT '' COMMENT '化疗时间（月）',
  `special_information_record` text DEFAULT NULL COMMENT '特殊信息记录',
  `follow_up_principal` varchar(100) NOT NULL DEFAULT '' COMMENT '随访负责人',
  `follow_up_note` text DEFAULT NULL COMMENT '随访备注',
  `follow_up_information_record` text DEFAULT NULL COMMENT '随访信息记录',
  `created_at` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='胃ca随访表';

DROP TABLE IF EXISTS `syy_stromal_tumors`;
CREATE TABLE `syy_stromal_tumors` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `admin_id` int(11) NOT NULL DEFAULT 0 COMMENT '管理员id',
  `img_id` varchar(20) NOT NULL DEFAULT '' COMMENT '图片id',
  `video_id` int(11) NOT NULL DEFAULT 0 COMMENT '视频id',
  `attachment_id` varchar(20) NOT NULL DEFAULT '' COMMENT '附件id',
  `hospital_number` varchar(50) NOT NULL DEFAULT '' COMMENT '住院号',
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '姓名',
  `sex` tinyint(3) NOT NULL DEFAULT 0 COMMENT '1:男 2：女',
  `age` int(11) NOT NULL DEFAULT 0 COMMENT '年龄',
  `national` varchar(50) NOT NULL DEFAULT '' COMMENT '民族',
  `id_card` varchar(50) NOT NULL DEFAULT '' COMMENT '身份证号',
  `mobile` varchar(50) NOT NULL DEFAULT '' COMMENT '患者联系电话',
  `total_money` varchar(50) NOT NULL DEFAULT '' COMMENT '住院总费用',
  `remark` text DEFAULT NULL COMMENT '备注',
  `family_contact` varchar(100) NOT NULL DEFAULT '' COMMENT '家属联系方式',
  `preoperative_chemotherapy` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术前是否化疗 0：否 1：是',
  `preoperative_chemotherapy_laparoscopic_exploration` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术前化疗前是否腹腔镜探查 0：否 1：是',
  `laparoscopic_exploration_time` int(11) NOT NULL DEFAULT 0 COMMENT '腹腔镜探查时间',
  `laparoscopic_exploration_result` tinyint(3) NOT NULL DEFAULT 0 COMMENT '腹腔镜探查结果 1：无腹膜转移 2：有腹膜转移',
  `preoperative_chemotherapy_scheme` text DEFAULT NULL COMMENT '术前化疗方案',
  `preoperative_chemotherapy_period` varchar(100) NOT NULL DEFAULT '' COMMENT '术前化疗时间周期',
  `chemotherapy_operative` tinyint(3) NOT NULL DEFAULT 0 COMMENT '化疗后是否手术 0：否 1：是',
  `chemotherapy_adverse_reactions` text DEFAULT NULL COMMENT '化疗期间不良反应',
  `accept_chemotherapy_clinic_evaluate` tinyint(3) NOT NULL DEFAULT 0 COMMENT '接受化疗后临床评价 1：cr 2:pr 3:sd 4:pd',
  `operative_evaluate_effect` text DEFAULT NULL COMMENT '术后病理评效',
  `admission_time` int(11) NOT NULL DEFAULT 0 COMMENT '入院日期时间',
  `operative_time` int(11) NOT NULL DEFAULT 0 COMMENT '手术日期时间',
  `discharge_time` int(11) NOT NULL DEFAULT 0 COMMENT '出院日期时间',
  `total_hospital_days` varchar(50) NOT NULL DEFAULT 0 COMMENT '总住院时间（天）',
  `postoperation_hospital_days` int(11) NOT NULL DEFAULT 0 COMMENT '术后住院时间（天）',
  `ecog_score` varchar(50) NOT NULL DEFAULT '' COMMENT 'ecog 评分',  
  `nrs2002_score` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'nrs2002评分 0: <3 1: >=3',
  `nutrition_support_therapy` tinyint(3) NOT NULL DEFAULT 0 COMMENT '营养支持治疗 0：无 1：有',
  `scheme` tinyint(3) NOT NULL DEFAULT 0 COMMENT '方案：1：ten 2:pn+en 3:tpn',
  `days` varchar(100) NOT NULL DEFAULT '' COMMENT '天数（d）',
  `asa_grade` varchar(100) NOT NULL DEFAULT '' COMMENT 'asa分级',
  `main_symptoms` varchar(100) NOT NULL DEFAULT '0' COMMENT '主要症状 0：无 1：腹痛 2：饱胀 3：呕吐 4：呕血 5：便血 6：黑便 7：吞咽困难 8：烧心感 9：厌食 10：乏力 11：体重下降 12：返酸 13：暖气 14：呃逆 15：其他',
  `main_signs` varchar(100) NOT NULL DEFAULT '0' COMMENT '主要体征 0：无 1：腹部压痛 2：腹部包块 3：腹肌抵抗 4：胃型 5：肛检包块/结节 6：振水音 7：左锁骨上淋巴结肿大 8：移动性浊音 9：其他',
  `laparoscopic_operative_record` text DEFAULT NULL COMMENT '腹腔手术史',
  `abdominal_surgery` text DEFAULT NULL COMMENT '腹腔手术',
  `family_record` text DEFAULT NULL COMMENT '家族史',
  `smoke` tinyint(3) NOT NULL DEFAULT 0 COMMENT '吸烟 0：无 1：有',
  `smoke_year` varchar(50) NOT NULL DEFAULT 0 COMMENT '吸烟（年）',
  `average_smoke_day` varchar(30) NOT NULL DEFAULT '' COMMENT '平均（支/天）',
  `drink` tinyint(3) NOT NULL DEFAULT 0 COMMENT '饮酒 0：无 1：有',
  `drink_year` varchar(30) NOT NULL DEFAULT '' COMMENT '饮酒年',
  `average_drink_day` varchar(30) NOT NULL DEFAULT '' COMMENT '平均（g/天）',
  `height` varchar(30) NOT NULL DEFAULT '' COMMENT '身高cm',
  `weight` varchar(30) NOT NULL DEFAULT '' COMMENT '体重kg',
  `bmi` text DEFAULT NULL COMMENT 'bmi',
  `hp` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'hp 0:阴性 1：阳性',
  `ecg` tinyint(3) NOT NULL DEFAULT 0 COMMENT '心电图 0：无特殊 1：特殊异常',
  `preoperative_lung_function` text DEFAULT NULL COMMENT '术前肺功能fev1/fvc(%)',
  `preoperative_complications_check_exception` varchar(500) NOT NULL DEFAULT '' COMMENT '术前合并症/术前检查异常',
  `preoperative_complications_0` varchar(100) NOT NULL DEFAULT '0' COMMENT '术前合并症 0：无 1：出血 2：穿孔',
  `preoperative_complications` varchar(100) NOT NULL DEFAULT '0' COMMENT '术前合并症　　１＝呼吸系统（COPD，哮喘，肺心病）；２＝循环系统（高血压，心功能不全（NYHA Ⅲ或Ⅳ)，陈旧性心肌梗塞）；３＝消化系统（肝炎，肝硬化，门脉高压，消化道溃疡，炎性肠病）；４＝内分泌（甲亢，糖尿病）；５＝泌尿系统（慢性肾炎，肾功能不全）；６＝神经系统（陈旧性脑梗塞）７＝患有其他恶性疾病：疾病名称；８＝免疫疾病后长期服用免疫抑制剂；９＝凝血机制异常或长期使用抗凝药物；１０＝其他：具体情况',
  `preoperative_chest_ct` text DEFAULT NULL COMMENT '术前胸部CT       0=正常，1=慢支，2=肺气肿，3=肺部感染，4=胸水，5=心脏长大，6=肺部占位，7=肿瘤肺部转移：具体部位',
  `laparoscopic_fat_volumne` text DEFAULT NULL COMMENT '腹腔内脂肪容积',
  `napes_fat_volumne` text DEFAULT NULL COMMENT '腹壁脂肪容积',
  `rbc` text DEFAULT NULL COMMENT 'rbc',
  `hemoglobin` varchar(100) NOT NULL DEFAULT '' COMMENT '血红蛋白（g/l）',
  `gpt` varchar(100) NOT NULL DEFAULT '' COMMENT '谷丙转氨酶alt u/l',
  `got` varchar(100) NOT NULL DEFAULT '' COMMENT '谷草转氨酶ast u/l',
  `tbil` varchar(100) NOT NULL DEFAULT '' COMMENT '总胆红素tbil mmol/l',
  `tp` varchar(100) NOT NULL DEFAULT '' COMMENT '总蛋白tp g/l',
  `alb` varchar(100) NOT NULL DEFAULT '' COMMENT '白蛋白 alb g/l',
  `palb` varchar(100) NOT NULL DEFAULT '' COMMENT '前白蛋白 palb g/l',
  `glu` text DEFAULT NULL COMMENT 'glu',
  `ua` text DEFAULT NULL COMMENT 'ua',  
  `crea` text DEFAULT NULL COMMENT 'crea',
  `d_dimer` text DEFAULT NULL COMMENT 'd-dimer',
  `blood_type` tinyint(3) NOT NULL DEFAULT 0 COMMENT '血型 1：a 2:b 3:o 4:ab',
  `preoperative_afp` text DEFAULT NULL COMMENT '术前afp',
  `preoperative_cea` text DEFAULT NULL COMMENT '术前cea',
  `preoperative_ca19_9` text DEFAULT NULL COMMENT '术前ca19-9',
  `preoperative_ca125` text DEFAULT NULL COMMENT '术前ca125',
  `preoperative_ca15_3` text DEFAULT NULL COMMENT '术前ca15-3',
  `preoperative_ca72_4` text DEFAULT NULL COMMENT '术前ca72-4',
  `stool_ob` tinyint(3) NOT NULL DEFAULT 0 COMMENT '大便隐血 0:阴 1：阳',
  `postoperative_afp` text DEFAULT NULL COMMENT '术后afp',
  `postoperative_cea` text DEFAULT NULL COMMENT '术后cea',
  `postoperative_ca19_9` text DEFAULT NULL COMMENT '术后ca19-9',
  `postoperative_ca72_4` text DEFAULT NULL COMMENT '术后ca72-4',
  `postoperative_ca125` text DEFAULT NULL COMMENT '术后125',
  `postoperative_ca15_3` text DEFAULT NULL COMMENT '术后ca15-3',
  `postoperative_her2` text DEFAULT NULL COMMENT '术后her2',
  `postoperative_rbc` text DEFAULT NULL COMMENT '术后rbc',
  `postoperative_hemoglobin` text DEFAULT NULL COMMENT '术后血红蛋白',
  `postoperative_gpt` varchar(100) NOT NULL DEFAULT '' COMMENT '术后谷丙转氨酶alt u/l',
  `postoperative_got` varchar(100) NOT NULL DEFAULT '' COMMENT '术后谷草转氨酶ast u/l',
  `postoperative_tbil` varchar(100) NOT NULL DEFAULT '' COMMENT '术后总胆红素tbil mmol/l',
  `postoperative_tp` varchar(100) NOT NULL DEFAULT '' COMMENT '术后总蛋白tp g/l',
  `postoperative_alb` varchar(100) NOT NULL DEFAULT '' COMMENT '术后白蛋白 alb g/l',
  `postoperative_glu` varchar(100) NOT NULL DEFAULT '' COMMENT '术后glu',
  `postoperative_ua` varchar(100) NOT NULL DEFAULT '' COMMENT '术后ua',
  `postoperative_crea` varchar(100) NOT NULL DEFAULT '' COMMENT '术后crea',
  `postoperative_d_d2` text DEFAULT NULL COMMENT 'postoperative_d-d2',
  `surgeon` varchar(100) NOT NULL DEFAULT '' COMMENT '术者',
  `location` tinyint(3) NOT NULL DEFAULT 0 COMMENT '位置 1=胃腔内；2=胃腔外；3=小肠；4=直肠',
  `road` tinyint(3) NOT NULL DEFAULT 0 COMMENT '入路(1=开腹，2=腹腔镜，3=经直肠)',
  `laparoscopic_exploration_laparoscopy` text DEFAULT NULL COMMENT '腹腔镜探查后中转开腹原因 具体',
  `removal_way` tinyint(3) NOT NULL DEFAULT 0 COMMENT '切除方式(1=DG，2=TG，3=PG,4=局部切除)',
  `consistent_with_nail` text DEFAULT NULL COMMENT '吻合钉',
  `rebuild` tinyint(3) NOT NULL DEFAULT 0 COMMENT '重建(1=Billroth-1，2=Billroth-2，3=Roux-en-Y，4=Braun)',
  `coated_complete` tinyint(3) NOT NULL DEFAULT 0 COMMENT '包膜完整 0：不完整 1：完整',
  `intraoperative_organ_injury_occurred` varchar(100) NOT NULL DEFAULT '0' COMMENT '术中并发器官损伤(0=无，1=脾脏，2=肝，3=胰，4=横结肠，5=胆囊，6=小肠)',
  `intraoperative_organ_injury_occurred_handle` text DEFAULT NULL COMMENT '术中并发症-处理',
  `intraoperative_complications_bleeding_site` text DEFAULT NULL COMMENT '术中并发症-出血部位',
  `intraoperative_complications_bleeding_handle` text DEFAULT NULL COMMENT '术中并发症-出血处理',
  `operation_minutes` varchar(100) NOT NULL DEFAULT '' COMMENT '手术时间（分）',
  `intraoperative_blood_loss_was_estimated` varchar(100) NOT NULL DEFAULT '' COMMENT '术中估计出血量ml',
  `perioperative_blood_transfusion` tinyint(3) NOT NULL DEFAULT 0 COMMENT '围术期输血(0=未输血；1=术前；2=术中；3=术后；RBC，FFP，ALB。eg: 1-RBC 2U, 3-FFP 200ml)',
  `adverse_reactions_of_perioperative_blood_transfusion` varchar(100) NOT NULL DEFAULT '0' COMMENT '围术期输血不良反应(0=无；1=发热；2=过敏；3=溶血；4=其它)',
  `perioperative_transfusion_unit` varchar(100) NOT NULL DEFAULT '' COMMENT '围术期输血单位',
  `ascites` tinyint(3) NOT NULL DEFAULT 0 COMMENT '腹水(0:无; 1:少量；2：中量；3：大量)',
  `cancer_cell` tinyint(3) NOT NULL DEFAULT 0 COMMENT ' 0=CY0:腹腔脱落癌细胞检查,未见癌细胞;     1=CY1: 找到癌细胞;    X=CYX:未做腹腔脱落癌细胞检查。',
  `peritoneal_metastasis` tinyint(3) NOT NULL DEFAULT 0 COMMENT '腹膜转移（0=P0 无腹膜扩散）；1=P1 癌灶附近腹膜，大网膜及横结肠系膜种植）；2=P2 横结肠下及膈肌腹膜少数癌灶）；3=P3 远处腹膜多数癌灶种植）；4=Px 腹膜转移无法判断）',
  `hepatic_metastases` text DEFAULT NULL COMMENT '肝转移(0:无; 1:具体)',
  `single_hepatic_metastases` tinyint(3) NOT NULL DEFAULT 0 COMMENT '单个肝转移（１＝左叶；２＝右叶）',
  `more_hepatic_metastases` tinyint(3) NOT NULL DEFAULT 0 COMMENT '多个肝转移（１＝左叶；２＝右叶；3=左右叶均有）',
  `lymph_nodes_were_enlarged_in_16` text DEFAULT NULL COMMENT '腹膜后、肠系膜根部、16组淋巴结肿大',
  `number_of_tumor_lesions` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肿瘤病灶个数 1=单病灶；2=双病灶；3=三病灶及更多',
  `longitudinal_position_of_a_single_lesion` tinyint(3) NOT NULL DEFAULT 0 COMMENT '单病灶肿瘤纵向部位(1=胃上部U，2=胃体M，3=胃下部L，4=U+食管受累E，5=UM/MU，6=LM/ML，7=L+十二指肠受累D，8=LMU/MLU/MUL/UML)',
  `aeg` tinyint(3) NOT NULL DEFAULT 0 COMMENT '食管胃结合部腺癌  0=否，1=siewert-I型，2=siewert-II型，3=siewert-III型',
  `peridiameter_of_the_tumor` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肿瘤周径部位(1=小弯，2=大弯，3=前壁，4=后壁，5=全周)',
  `greatest_tumor_diameter` varchar(100) NOT NULL DEFAULT '' COMMENT '肿瘤最大径（如果为双病灶肿瘤描述主体病灶）(cm)',
  `distance_between_the_proximal_margin_and_the_tumor` varchar(100) NOT NULL DEFAULT '' COMMENT '近切缘距肿瘤距离cm',
  `distance_of_distal_margin_to_tumor` varchar(100) NOT NULL DEFAULT '' COMMENT '远切缘距肿瘤距离cm',
  `detection_of_frozen_cutting_edge_disease` text DEFAULT NULL COMMENT '冰冻切缘病检',
  `level_of_tumor` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肿瘤级别（gist-风险级别） 1：低风险 2：高风险',
  `gist_tnm_aging` text DEFAULT NULL COMMENT 'GIST TNM分期',
  `resect_the_inspection_margin_again` tinyint(3) NOT NULL DEFAULT 0 COMMENT '再次切除送检切缘  0=无需再次送检，1：食管断端阴性；2：十二指肠断端阴性；3：胃大弯阴性；4：胃小弯阴性',
  `greater_omentum_margin_was_examined` tinyint(3) NOT NULL DEFAULT 0 COMMENT '大网膜边缘送检：0=阴性；1=阳性',
  `examination_of_lesser_omentum_margin` tinyint(3) NOT NULL DEFAULT 0 COMMENT '小网膜边缘送检：0=阴性；1=阳性',
  `her2` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'HER2(0=0;1=1+;2=2+;3=3+;4=4+)',
  `stage_show` text DEFAULT NULL COMMENT '分期说明（术前MDCT，术中特殊发现，术后病理特殊信息）',
  `pathology_num` varchar(100) NOT NULL DEFAULT '' COMMENT '病理号（另自行保存病理报告副本pdf文档，以病理号命名）',
  `perioperative_nutritional_support` text DEFAULT NULL COMMENT '围术期营养支持(包括具体方案，持续时间，不良反应)',
  `perioperative_antibiotics` text DEFAULT NULL COMMENT '围术期抗生素',
  `postoperative_prophylactic_antibiotic` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术后预防抗生素(1=常规用法，2=短程用法)',
  `perioperative_acid_suppressor` text DEFAULT NULL COMMENT '围术期抑酸剂',
  `perioperative_mucosal_protectant` text DEFAULT NULL COMMENT '围术期黏膜保护剂',
  `perioperative_hemostatic_agent` text DEFAULT NULL COMMENT '围术期止血药(0:无; 1:具体)',
  `perioperative_somatostatin` tinyint(3) NOT NULL DEFAULT 0 COMMENT '围术期生长抑素(0=无，1=有)',
  `perioperative_analgesics` text DEFAULT NULL COMMENT '围术期镇痛药',
  `perioperative_intensive_care` text DEFAULT NULL COMMENT '围术期重症监护',
  `other_special_treatments_during_perioperative_period` text DEFAULT NULL COMMENT '围术期其他特殊处理',
  `whether_to_install_a_gastric_tube` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否安置胃管（1，是；2，否）',
  `set_time` int(11) NOT NULL DEFAULT 0 COMMENT '安置时间（1，术前；2、术中；3，术后）',
  `extraction_date_of_gastric_tube_time` int(11) NOT NULL DEFAULT 0 COMMENT '胃管拔除日(POD)',
  `average_daily_gastric_fluid_volume` varchar(100) NOT NULL DEFAULT '' COMMENT '每日平均胃液量(ml)',
  `cause_of_gastric_tube_replacement` text DEFAULT NULL COMMENT '再次安置胃管原因：具体描述',
  `catheter_removal_time` int(11) NOT NULL DEFAULT 0 COMMENT '尿管拔除时间(POH)',
  `abdominal_drainage_tube_removal_date_time` int(11) NOT NULL DEFAULT 0 COMMENT '腹腔引流管拔除日(POD)',
  `average_daily_volume_of_abdominal_drainage_fluid` varchar(100) NOT NULL DEFAULT '' COMMENT '每日平均腹腔引流液量(ml)',
  `anal_exhaust_day_time` int(11) NOT NULL DEFAULT 0 COMMENT '肛门排气日(h)', 
  `start_an_out_of_bed_day_time` int(11) NOT NULL DEFAULT 0 COMMENT '开始下床活动日(POH)',
  `start_a_fluid_day_time` int(11) NOT NULL DEFAULT 0 COMMENT '开始进食流质日(POH)',
  `highest_temperature` varchar(100) NOT NULL DEFAULT '' COMMENT '最高体温(℃)',
  `postoperative_temperature_greater_than_38_days` varchar(100) NOT NULL DEFAULT '' COMMENT '术后体温>38℃天数(day)',
  `perioperative_complications` varchar(100) NOT NULL DEFAULT '0' COMMENT '围术期手术并发症(0=无；1=十二指肠残端瘘，2=吻合口瘘，3=胰瘘/胰腺炎，4=肠瘘，5=胆瘘，6=淋巴乳糜瘘，7=腹腔内出血，8=消化道出血，9=麻痹性肠梗阻，10=机械性梗阻，11=胃无张力，12=切口感染/切口裂开，13=腹腔感染/腹腔脓肿/腹腔局限性积液，14=血管损伤，15=临近器官损伤，16=腹腔镜相关并发症)',
  `management_of_perioperative_complications` text DEFAULT NULL COMMENT '围术期手术并发症处理方式',
  `nonoperative_complication` text DEFAULT NULL COMMENT '非手术并发症',
  `perioperative_management_of_nonoperative_complications` text DEFAULT NULL COMMENT '围术期非手术并发症处理方式',
  `outcome` tinyint(3) NOT NULL DEFAULT 0 COMMENT '转归(1=无并发症出院，2=并发症治愈出院，3=自动出院，4=死亡)',
  `inputting_medical_records` varchar(100) NOT NULL DEFAULT '' COMMENT '病历信息录入者',
  `is_the_record_entry_complete` text DEFAULT NULL COMMENT '病历录入是否完整',
  `medical_records_information_checker` varchar(100) NOT NULL DEFAULT '' COMMENT '病历信息核查者',
  `created_at` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='间质瘤表';

DROP TABLE IF EXISTS `syy_stromal_tumor_follow_ups`;
CREATE TABLE `syy_stromal_tumor_follow_ups` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `stromal_tumor_id` int(11) NOT NULL DEFAULT 0 COMMENT '间质瘤 id',
  `dead_time` int(11) NOT NULL DEFAULT 0 COMMENT '死亡日期时间(月)',
  `survival_month` varchar(100) NOT NULL DEFAULT '' COMMENT '生存月份',
  `followed_up_after_operation_date_time` int(11) NOT NULL DEFAULT 0 COMMENT '术后随访日期时间',
  `results_were_followed_up_after_operation` varchar(500) NOT NULL DEFAULT '' COMMENT '随访结局，1=无瘤生存；2=带瘤生存；3=肿瘤原因死亡；4=其他原因死亡；5=失访，原因 ',
  `long_term_complications_and_management_methods` text DEFAULT NULL COMMENT '远期并发症及处理方式',
  `whether_new_hair_gallbladder_stone` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否新发胆囊结石（0=否；1=是，2=既往合并胆囊结石）',
  `gallstone_discovery_time` int(11) NOT NULL DEFAULT 0 COMMENT '胆囊结石发现时间（年-月-日）',
  `treatment_of_gallstones` tinyint(3) NOT NULL DEFAULT 0 COMMENT '胆囊结石处理方式（1=保守，2=手术）',
  `local_recurrence_time` int(11) NOT NULL DEFAULT 0 COMMENT '局部复发时间',
  `distant_transfer_time` int(11) NOT NULL DEFAULT 0 COMMENT '远处转移时间',
  `distant_metastatic_site` varchar(300) NOT NULL DEFAULT '' COMMENT '远处转移部位（非肿瘤死亡原因）',
  `whether_chemotherapy` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否化疗 0=无；1=有；2=新辅助',
  `chemotherapy_way` tinyint(3) NOT NULL DEFAULT 0 COMMENT '化疗途径  1=口服；2=静脉',
  `chemotherapy_regimens` text DEFAULT NULL COMMENT '化疗方案',
  `chemotherapy_regimen_rate` varchar(100) NOT NULL DEFAULT '' COMMENT '化疗疗程/次',
  `chemotherapy_month` varchar(100) NOT NULL DEFAULT '' COMMENT '化疗时间（月）',
  `special_information_record` text DEFAULT NULL COMMENT '特殊信息记录',
  `follow_up_principal` varchar(100) NOT NULL DEFAULT '' COMMENT '随访负责人',
  `follow_up_note` text DEFAULT NULL COMMENT '随访备注',
  `follow_up_information_record` text DEFAULT NULL COMMENT '随访信息记录',
  `created_at` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='间质瘤随访表';

DROP TABLE IF EXISTS `syy_colorectal_cancers`;
CREATE TABLE `syy_colorectal_cancers` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `admin_id` int(11) NOT NULL DEFAULT 0 COMMENT '管理员id',
  `img_id` varchar(20) NOT NULL DEFAULT '' COMMENT '图片id',
  `video_id` int(11) NOT NULL DEFAULT 0 COMMENT '视频id',
  `attachment_id` varchar(20) NOT NULL DEFAULT '' COMMENT '附件id',
  `hospital_number` varchar(50) NOT NULL DEFAULT '' COMMENT '住院号',
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '姓名',
  `sex` tinyint(3) NOT NULL DEFAULT 0 COMMENT '1:男 2：女',
  `age` int(11) NOT NULL DEFAULT 0 COMMENT '年龄',
  `national` varchar(50) NOT NULL DEFAULT '' COMMENT '民族',
  `id_card` varchar(50) NOT NULL DEFAULT '' COMMENT '身份证号',
  `mobile` varchar(50) NOT NULL DEFAULT '' COMMENT '患者联系电话',
  `total_money` varchar(50) NOT NULL DEFAULT '' COMMENT '住院总费用',
  `remark` text DEFAULT NULL COMMENT '备注',
  `family_contact` varchar(100) NOT NULL DEFAULT '' COMMENT '家属联系方式',
  `admission_time` int(11) NOT NULL DEFAULT 0 COMMENT '入院日期时间',
  `operative_time` int(11) NOT NULL DEFAULT 0 COMMENT '手术日期时间',
  `discharge_time` int(11) NOT NULL DEFAULT 0 COMMENT '出院日期时间',
  `total_hospital_days` varchar(50) NOT NULL DEFAULT 0 COMMENT '总住院时间（天）',
  `postoperation_hospital_days` int(11) NOT NULL DEFAULT 0 COMMENT '术后住院时间（天）',
  # 术前
  # 术前合并症及简单描述
  # 术前肠镜{A}
  `preoperative_colonoscopy_from_the_anus_a1` varchar(50) NOT NULL DEFAULT '' COMMENT '距肛门A1',
  `preoperative_colonoscopy_infringement_of_lumen_a2` varchar(50) NOT NULL DEFAULT '' COMMENT '侵犯肠腔A2',
  `preoperative_colonoscopy_whether_the_endoscope_passes_a3` varchar(50) NOT NULL DEFAULT '' COMMENT '内镜是否通过a3',
  `preoperative_colonoscopy_the_biopsy_results_a4` text DEFAULT NULL COMMENT '活检结果a4',
  # 术前分期{B}
  `preoperative_staging_ct_mri_t` varchar(50) NOT NULL DEFAULT '' COMMENT 't',
  `preoperative_staging_ct_mri_leaching_b1` varchar(50) NOT NULL DEFAULT '' COMMENT '侵出b1',
  `preoperative_staging_ct_mri_the_deepest_point_is_at_b2` tinyint(3) NOT NULL DEFAULT 0 COMMENT '1：前 2：左 3：右 4：后',
  `preoperative_staging_ct_mri_intestinal_separated_edge_mesangium` varchar(50) NOT NULL DEFAULT '' COMMENT '肠壁距系膜外缘b3',
  `preoperative_staging_ct_mri_t_from_outer_edge_mesangium_b4` varchar(50) NOT NULL DEFAULT '' COMMENT 't距系膜外缘b4',
  `preoperative_staging_ct_mri_n` varchar(50) NOT NULL DEFAULT '' COMMENT 'n',
  `preoperative_staging_ct_mri_the_largest_diameter_dmax` varchar(50) NOT NULL DEFAULT '' COMMENT '最大直径dmax',
  `preoperative_staging_ct_mri_number_of_lymph_nodes_no` varchar(50) NOT NULL DEFAULT '' COMMENT '淋巴结数目',
  `preoperative_staging_ct_mri_m` varchar(50) NOT NULL DEFAULT '' COMMENT 'm',
  `preoperative_staging_ct_mri_the_largest_diameter_dmax2` varchar(50) NOT NULL DEFAULT '' COMMENT '最大直径dmax2',
  `preoperative_staging_ct_mri_t3_mesenterin_and_deep` tinyint(3) NOT NULL DEFAULT 0 COMMENT 't3直肠系膜素及深度deep 1：t3i<=1/3 2:t3m<=2/3 3:t3o>=2/3',
  `preoperative_staging_ultrasonic_t` varchar(50) NOT NULL DEFAULT '' COMMENT '超声分期t',
  `preoperative_staging_ultrasonic_leaching_ultramundane` varchar(50) NOT NULL DEFAULT '' COMMENT '侵出ultramundane',
  `preoperative_staging_ultrasonic_n` varchar(50) NOT NULL DEFAULT '' COMMENT 'n',
  `preoperative_staging_ultrasonic_the_largest_diameter_d1` varchar(50) NOT NULL DEFAULT '' COMMENT '最大直径d1',
  `preoperative_staging_ultrasonic_m` varchar(50) NOT NULL DEFAULT '' COMMENT 'm',
  `preoperative_staging_ultrasonic_the_largest_diameter_d2` varchar(50) NOT NULL DEFAULT '' COMMENT '最大直径d2',
  `preoperative_staging_ultrasonic_pet_ct` varchar(50) NOT NULL DEFAULT '' COMMENT 'pet_ct',
  `preoperative_staging_clinical_t` varchar(50) NOT NULL DEFAULT '' COMMENT '临床分期t',
  `preoperative_staging_clinical_n` varchar(50) NOT NULL DEFAULT '' COMMENT 'n',
  `preoperative_staging_clinical_m` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'm 1：肝 2：肝疑 3：肺 4：肺疑 5：骨 6：骨疑 7：腹膜 8：腹膜疑 9：淋巴结 10：口渌口',
  `preoperative_staging_intestinal_tract_other` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肠道其他病灶 1：无 2：多源癌',
  `preoperative_staging_intestinal_tract_location` varchar(100) NOT NULL DEFAULT '' COMMENT '部位location',
  `preoperative_staging_intestinal_tract_staging_t` varchar(100) NOT NULL DEFAULT '' COMMENT '分期t',
  `preoperative_staging_intestinal_tract_n` varchar(100) NOT NULL DEFAULT '' COMMENT 'n',
  `preoperative_staging_intestinal_tract_unite` tinyint(3) NOT NULL DEFAULT 0 COMMENT '合并息肉 1：单个息肉 2：多个 3：fap 4：年幼性息肉病 5：pj综合征 6：其他',
  `preoperative_staging_imaging_circumferential_margin_situation` tinyint(3) NOT NULL DEFAULT 0 COMMENT '影像学环周切缘状况 1：明确未累及 2：crm受威胁（可疑）3：明确累及',
  `preoperative_staging_imaging_circumferential_margin_mdt_discuss` tinyint(3) NOT NULL DEFAULT 0 COMMENT '影像学环周切缘mdt讨论 1：是 2：否',
  `preoperative_staging_resectable_primary_lesion` tinyint(3) NOT NULL DEFAULT 0 COMMENT '原发灶可切除性 1：可切除 2：可转化 3：不可切除',
  `preoperative_staging_resectable_transition_lesion` tinyint(3) NOT NULL DEFAULT 0 COMMENT '转移灶可切除性 1：可切除 2：可转化 3：不可切除',
  `preoperative_staging_transition_type` tinyint(3) NOT NULL DEFAULT 0 COMMENT '转移类型 1：单器单灶 2：单器多灶 3：多器局限灶可切除 4：多器官多灶',
  `preoperative_staging_number_of_liver_metastases` varchar(50) NOT NULL DEFAULT '' COMMENT '肝转移灶数目no1',
  `preoperative_staging_number_of_liver_metastases_dg1` varchar(50) NOT NULL DEFAULT '' COMMENT '最大转移灶直径dg1',
  `preoperative_staging_number_of_liver_metastases_dg2` varchar(50) NOT NULL DEFAULT '' COMMENT '平均转移灶直径dg2',
  `preoperative_staging_number_of_liver_metastases_location1` tinyint(3) NOT NULL DEFAULT 0 COMMENT '转移灶部位location1 1：单肝 2：双肝',
  `preoperative_staging_number_of_lung_metastases` varchar(50) NOT NULL DEFAULT '' COMMENT '肺转移灶数目no2',
  `preoperative_staging_number_of_lung_metastases_df1` varchar(50) NOT NULL DEFAULT '' COMMENT '最大转移灶直径df1',
  `preoperative_staging_number_of_lung_metastases_df2` varchar(50) NOT NULL DEFAULT '' COMMENT '平均转移灶直径df2',
  `preoperative_staging_number_of_lung_metastases_location2` tinyint(3) NOT NULL DEFAULT 0 COMMENT '转移灶部位location2 1:单叶 2：单肺 3：双肺',
  `preoperative_staging_mdt_metastase_suggest1` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'mdt对转移灶处理意见 1：同期手术 2：分期先原发 3：分期先转移 4：新辅助化疗 5：辅助化疗 6：联合放疗 7：靶向 8：姑息处理',
  `preoperative_staging_mdt_primary_suggest2` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'mdt对原发灶处理意见 1：新辅助放化疗 2：新辅助放疗 3：新辅助化疗 4：直接手术 5：不手术',
  # 新辅助化疗
  `preoperative_neoadjuvant_chemotherapy_plan_project` tinyint(3) NOT NULL DEFAULT 0 COMMENT '方案 1：folfox 2:xelox 3:folfiri 4:folfoxiri 5:爱必妥 6：贝伐 7：血管介入 8：其他',  
  `preoperative_neoadjuvant_chemotherapy_begin` int(11) NOT NULL DEFAULT 0 COMMENT '开始时间',  
  `preoperative_neoadjuvant_chemotherapy_end` int(11) NOT NULL DEFAULT 0 COMMENT '结束时间',  
  `preoperative_neoadjuvant_chemotherapy_adverse_response_hb` varchar(50) NOT NULL DEFAULT '' COMMENT '不良反应hb',  
  `preoperative_neoadjuvant_chemotherapy_adverse_response_wbc` varchar(50) NOT NULL DEFAULT '' COMMENT '不良反应wbc',  
  `preoperative_neoadjuvant_chemotherapy_adverse_response_gra` varchar(50) NOT NULL DEFAULT '' COMMENT '不良反应粒细胞',  
  `preoperative_neoadjuvant_chemotherapy_adverse_response_plt` varchar(50) NOT NULL DEFAULT '' COMMENT '不良反应plt',  
  `preoperative_neoadjuvant_chemotherapy_liver_function` text DEFAULT NULL COMMENT '肝功能',
  `preoperative_neoadjuvant_chemotherapy_kidney_function` text DEFAULT NULL COMMENT '肾功能',
  `preoperative_neoadjuvant_chemotherapy_sickness` text DEFAULT NULL COMMENT '呕吐',
  `preoperative_neoadjuvant_chemotherapy_diarrhoea` text DEFAULT NULL COMMENT '腹泻',
  `preoperative_neoadjuvant_chemotherapy_astriction` text DEFAULT NULL COMMENT '便秘',
  `preoperative_neoadjuvant_chemotherapy_heart` text DEFAULT NULL COMMENT '心脏毒性',
  `preoperative_neoadjuvant_chemotherapy_allergy` text DEFAULT NULL COMMENT '过敏反应',
  `preoperative_neoadjuvant_chemotherapy_skin` text DEFAULT NULL COMMENT '手足皮肤反应',
  `preoperative_neoadjuvant_chemotherapy_nerve` text DEFAULT NULL COMMENT '感觉神经病',
  `preoperative_neoadjuvant_chemotherapy_other` text DEFAULT NULL COMMENT '其他',
  `preoperative_neoadjuvant_chemotherapy_eva_clinical_efficacy` tinyint(3) NOT NULL DEFAULT 0 COMMENT '临床疗效评估 1：cr 2:pr 3:sd 4:pd 5:不详',
  `preoperative_neoadjuvant_chemotherapy_eva_pathological_efficacy` tinyint(3) NOT NULL DEFAULT 0 COMMENT '病理疗效评估 1：cr 2:pr 3:sd 4:pd 5:不详',
  # 新辅助放疗
  `preoperative_neoadjuvant_radiotherapy_dismember` tinyint(3) NOT NULL DEFAULT 0 COMMENT '剂量分割 1：常规分割 2：大分割',
  `preoperative_neoadjuvant_radiotherapy_technology` tinyint(3) NOT NULL DEFAULT 0 COMMENT '放疗技术 1：3D-RCT 2：imrt 3:igrt',
  `preoperative_neoadjuvant_radiotherapy_dose` varchar(100) NOT NULL DEFAULT '' COMMENT '剂量',
  `preoperative_neoadjuvant_radiotherapy_synchro` tinyint(3) NOT NULL DEFAULT 0 COMMENT '同步化疗方案 1：xeloda 2:folfox 3:xelox 4:folfiri 5:folfoxiri 6:贝伐',
  `preoperative_neoadjuvant_radiotherapy_begin` int(11) NOT NULL DEFAULT 0 COMMENT '开始时间',
  `preoperative_neoadjuvant_radiotherapy_end` int(11) NOT NULL DEFAULT 0 COMMENT '结束时间',
  `preoperative_neoadjuvant_radiotherapy_metastatic_therapy_effect` tinyint(3) NOT NULL DEFAULT 0 COMMENT '转移灶治疗效果 1：完全缓解 2：部分缓解 3：疾病稳定 4：疾病进展',
  `preoperative_neoadjuvant_radiotherapy_curative_primary_les_ass` tinyint(3) NOT NULL DEFAULT 0 COMMENT '原发灶疗效评估 1:cr 2:pr 3:sd 4:pd 5:不详',
  `preoperative_neoadjuvant_radiotherapy_primary_pathology_ass` tinyint(3) NOT NULL DEFAULT 0 COMMENT '原发灶病理评估 1:cr 2:pr 3:sd 4:pd 5:不详',
  # 肠道狭窄状况评估
  `preoperative_assessment_intestinal_stenosis_exhaust` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肛门排气 1：正常 2：排气减少',
  `preoperative_assessment_intestinal_stenosis_defecate` tinyint(3) NOT NULL DEFAULT 0 COMMENT '排便情况 1：排便正常 2：便秘与腹泻交替 3：便秘小于1/3日 4：便秘小于1/7日 5：便秘大于1/7日',
  `preoperative_assessment_intestinal_stenosis_distension` tinyint(3) NOT NULL DEFAULT 0 COMMENT '腹胀 1：无 2：明显 3：腹部膨隆 4：肠型',
  `preoperative_assessment_intestinal_stenosis_enteroscope` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肠镜 1：顺利通过 2：通过阻力大 3：不能通过',
  `preoperative_assessment_intestinal_stenosis_shape` tinyint(3) NOT NULL DEFAULT 0 COMMENT '大便形状 1：正常成型 2：成型变细 3：常有糊状便 4：粘液糊状便 5：仅黏液便或便血无或很少粪渣',
  `preoperative_assessment_intestinal_stenosis_ct_proximal_bowel` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'ct近端肠管 1：空虚 2：干便无扩张 3：干便伴扩张 4:扩张伴积液但无肠壁肿胀增厚 5：扩张积液伴肠壁肿胀增厚 6：高度扩张积液',
  `preoperative_assessment_intestinal_stenosis_ct_maximum_left` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'ct左结肠最大直径 1：小于2.5 2：2.5-4 3：4-6 4：7-8 5：大于8',
  `preoperative_assessment_intestinal_stenosis_ct_x_imaging` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'ct或x造影 1：顺利通过 2：造影明显狭窄 3：造影不能通过',
  `preoperative_assessment_intestinal_stenosis_imaging_smallest` tinyint(3) NOT NULL DEFAULT 0 COMMENT '造影肠腔最小径 1：大于2 2：2-1 3：1-0.5 4：小于0.5',
  `preoperative_assessment_intestinal_stenosis_drugs_relieve` tinyint(3) NOT NULL DEFAULT 0 COMMENT '药物可否缓解便秘 1：灌肠能缓解 2：灌肠不能缓解 3：缓泻剂能缓解 4：缓泻剂不能缓解',
  `preoperative_assessment_intestinal_stenosis_juice` tinyint(3) NOT NULL DEFAULT 0 COMMENT '服洗肠液 1：排空好 2：腹痛胀可排空 3：部分排出 4：未排出或仅少量排便 5：急性肠梗阻',
  `preoperative_assessment_intestinal_stenosis_group` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术前分组 1：t3浅/n0 2：t3深/n1',
  `preoperative_assessment_intestinal_stenosis_asa` text DEFAULT NULL COMMENT '评分asa',
  `preoperative_assessment_intestinal_stenosis_new_neoadjuvant` tinyint(3) NOT NULL DEFAULT 0 COMMENT '新辅助治疗 1：无 2：短程放疗 3：长程放疗 4：放化疗 5：靶向 6：介入',
  `preoperative_assessment_intestinal_stenosis_autar` tinyint(3) NOT NULL DEFAULT 0 COMMENT '出诊时深静脉血栓autar评分 1：低风险小于等于10分 2：中风险11-14分 3：高风险大于等于15分',
  `preoperative_assessment_intestinal_stenosis_test_wbc` varchar(50) NOT NULL DEFAULT '' COMMENT 'wbc',
  `preoperative_assessment_intestinal_stenosis_test_hb` varchar(50) NOT NULL DEFAULT '' COMMENT 'hb',
  `preoperative_assessment_intestinal_stenosis_test_alb` varchar(50) NOT NULL DEFAULT '' COMMENT 'alb',
  `preoperative_assessment_intestinal_stenosis_test_cea` varchar(50) NOT NULL DEFAULT '' COMMENT 'cea',
  `preoperative_assessment_intestinal_stenosis_test_alt` varchar(50) NOT NULL DEFAULT '' COMMENT 'alt',
  `preoperative_assessment_intestinal_stenosis_test_tb` varchar(50) NOT NULL DEFAULT '' COMMENT 'tb',
  `preoperative_assessment_intestinal_stenosis_test1_wbc` varchar(50) NOT NULL DEFAULT '' COMMENT 'wbc',
  `preoperative_assessment_intestinal_stenosis_test1_hb` varchar(50) NOT NULL DEFAULT '' COMMENT 'hb',
  `preoperative_assessment_intestinal_stenosis_test1_alb` varchar(50) NOT NULL DEFAULT '' COMMENT 'alb',
  `preoperative_assessment_intestinal_stenosis_test1_cea` varchar(50) NOT NULL DEFAULT '' COMMENT 'cea',
  `preoperative_assessment_intestinal_stenosis_test1_alt` varchar(50) NOT NULL DEFAULT '' COMMENT 'alt',
  `preoperative_assessment_intestinal_stenosis_test1_tb` varchar(50) NOT NULL DEFAULT '' COMMENT 'tb',
  `preoperative_assessment_intestinal_stenosis_cancer_family` tinyint(3) NOT NULL DEFAULT 0 COMMENT '癌家族史 1：无 2：1个家属 3：2个家属 4：4个以上家属 5：fap家族 6：lynch综合征',
  `preoperative_assessment_intestinal_stenosis_manometry` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否肛门测压 1：是 2：否',
  `preoperative_assessment_intestinal_stenosis_mdt_compliance` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'mdt讨论结果依从性 1：完全依从 2：未完全依从',
  `preoperative_assessment_intestinal_stenosis_uncompl_reason` tinyint(3) NOT NULL DEFAULT 0 COMMENT '未依从原因 1：经济因素 2：病情进展 3：医疗因素',
  # 术中
  `intraoperative_operation_type` tinyint(3) NOT NULL DEFAULT 0 COMMENT '手术类型 1：择期 2：急诊',
  `intraoperative_colorectal_cancer_situation` tinyint(3) NOT NULL DEFAULT 0 COMMENT '直肠癌状况 1：无特殊 2：不全性肠梗阻 3：急性肠梗阻/穿孔 4：肠梗阻支架放置后 5：大出血 6：无梗阻但肠准备差 7：复发性直肠癌',
  `intraoperative_primary_lesion_anus` varchar(50) NOT NULL DEFAULT '' COMMENT '原发病灶 指检-距肛门',
  `intraoperative_primary_lesion_anus1` varchar(50) NOT NULL DEFAULT '' COMMENT '原发病灶 肠镜-距肛门',
  `intraoperative_location` tinyint(3) NOT NULL DEFAULT 0 COMMENT '位置 1：反折上 2：反折 3：反折下 4：肛管',
  `intraoperative_tumor_infringe_loop` tinyint(3) NOT NULL DEFAULT 0 COMMENT '位置 1：小于等于1/4周 2：1/3周 3：1/2周 4：3/4周 5：一周',
  `intraoperative_tumor_size` varchar(50) NOT NULL DEFAULT '' COMMENT '肿瘤大小',
  `intraoperative_antetheca` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否累及反折下直肠前壁 1：是 2：否',
  `intraoperative_tumor_deepest` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肿瘤最深处位于 1：前 2：后 3：左侧 4：左前 5：左后 6：右侧 7：右后',
  `intraoperative_classification` tinyint(3) NOT NULL DEFAULT 0 COMMENT '大体分型 1：肿块 2：溃疡型 3：侵润型',
  `intraoperative_perforate` tinyint(3) NOT NULL DEFAULT 0 COMMENT '穿孔 1：是 2：否',
  `intraoperative_circumference` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否侵犯肠周组织器官 1：是 2：否',
  `intraoperative_invaded_tissues_and_organ_situation` text DEFAULT NULL COMMENT '受侵组织器官情况',
  `intraoperative_distance_metastasis` tinyint(3) NOT NULL DEFAULT 0 COMMENT '远处转移 1：是 2：否',
  `intraoperative_metastasis_part` tinyint(3) NOT NULL DEFAULT 0 COMMENT '转移部位 1：腹膜转移 2：肝转移 3：肺转移 4：骨转移 5：淋巴转移 6：其他',
  `intraoperative_degree_cure` tinyint(3) NOT NULL DEFAULT 0 COMMENT '根治度 1：根治术 2：姑息术 3：无法切除',
  `intraoperative_opera_way` tinyint(3) NOT NULL DEFAULT 0 COMMENT '手术方式 1：开腹 2：腹腔镜 3：手辅助 4：腔镜中转',
  `intraoperative_opera_way_reason` text DEFAULT NULL COMMENT '腔镜中转原因',
  `intraoperative_remove_way` tinyint(3) NOT NULL DEFAULT 0 COMMENT '切除方式 1：miles 2:elape 3:dixon 4:dixon拖出dst 5：hartmann 6:经肛局切 7：isr或parks改良 8：其他',
  `intraoperative_lymph_node_clean` tinyint(3) NOT NULL DEFAULT 0 COMMENT '淋巴结清扫 1：d1 2:d2 3:d3',
  `intraoperative_side_clean` tinyint(3) NOT NULL DEFAULT 0 COMMENT '侧方清扫 1：否 2：左侧 3：右侧 4：双侧 5：超范围',
  `intraoperative_fit_way` tinyint(3) NOT NULL DEFAULT 0 COMMENT '吻合方式 1：端侧 2：端端 3：j-pouch',
  `intraoperative_pre_fistulation` tinyint(3) NOT NULL DEFAULT 0 COMMENT '预防性造痿 1：是 2：否',
  `intraoperative_rebuilt_way` tinyint(3) NOT NULL DEFAULT 0 COMMENT '重建方式 1：结肛 2：结直肠',
  `intraoperative_anal_fit_way` tinyint(3) NOT NULL DEFAULT 0 COMMENT '结肛吻合方法 1：手工 2：器械',
  `intraoperative_stapling_size` tinyint(3) NOT NULL DEFAULT 0 COMMENT '吻合器大小 1：29mm 2:33mm',
  `intraoperative_anastomotic_distance` varchar(50) NOT NULL DEFAULT '' COMMENT '吻合口距肛门',
  `intraoperative_anal_canal` tinyint(3) NOT NULL DEFAULT 0 COMMENT '放置肛管 1：是 2：否',
  `intraoperative_spleen` tinyint(3) NOT NULL DEFAULT 0 COMMENT '游离脾曲 1：完全 2：脾曲下 3：降结肠',
  `intraoperative_predict_crm` tinyint(3) NOT NULL DEFAULT 0 COMMENT '预判crm 1：阳性 2：不确切 3：阴性',
  `intraoperative_self_evaluation_mesangial_integrity_anus` tinyint(3) NOT NULL DEFAULT 0 COMMENT '保肛手术 1：3a 2:3b 3:3c 4:2 5:1a 6:1b',
  `intraoperative_self_evaluation_mesangial_integrity_operate` tinyint(3) NOT NULL DEFAULT 0 COMMENT '手术miles 1：a(差) 2：b(标准) 3:c(超标准) 4:d(柱状切除)',
  `intraoperative_part_degree_cure` tinyint(3) NOT NULL DEFAULT 0 COMMENT '局部根治度 1：r0 2:r1 3:r2',
  `intraoperative_cancer_residual_part` text DEFAULT NULL COMMENT '癌残留部位',
  `intraoperative_unit_viscera_remove` tinyint(3) NOT NULL DEFAULT 0 COMMENT '联合脏器切除 1：无 2：有',
  `intraoperative_remove_organ` varchar(100) NOT NULL DEFAULT '' COMMENT '切除器官',
  `intraoperative_remove_reason` text DEFAULT NULL COMMENT '切除原因',
  `intraoperative_distal_incisor_margin_from_anterior` varchar(50) NOT NULL DEFAULT '' COMMENT '离体前远切缘',
  `intraoperative_proximal_to_the_anterior_margin_of_the_body` varchar(50) NOT NULL DEFAULT '' COMMENT '离体前近切缘',
  `intraoperative_lymph_node_clear_out_num` varchar(50) NOT NULL DEFAULT '' COMMENT '淋巴结清出总数',
  `intraoperative_ln_within_10cm_of_the_tumor` varchar(50) NOT NULL DEFAULT '' COMMENT '距肿瘤10cm以内ln',
  `intraoperative_ln_within_10_15cm_of_the_tumor` varchar(50) NOT NULL DEFAULT '' COMMENT '距肿瘤10-15cm以内ln',
  `intraoperative_ln_within_above_15cm_of_the_tumor` varchar(50) NOT NULL DEFAULT '' COMMENT '距肿瘤15cm以上ln',
  `intraoperative_central_group_ln` varchar(50) NOT NULL DEFAULT '' COMMENT '中央组ln',
  `intraoperative_lymph_node_left` varchar(50) NOT NULL DEFAULT '' COMMENT '左侧侧方淋巴结',
  `intraoperative_lymph_node_right` varchar(50) NOT NULL DEFAULT '' COMMENT '右侧侧方淋巴结',
  `intraoperative_completely_tme_residual_basin_wall_tissue` tinyint(3) NOT NULL DEFAULT 0 COMMENT '完全tme时：盆壁有无系膜组织残留 1：无 2：有',
  `intraoperative_completely_tme_residual_basin_wall_tissue_spec` tinyint(3) NOT NULL DEFAULT 0 COMMENT '残留具体 1：点状系膜残留，最大系膜残留小于1*1cm 2：薄片状系膜残留 3：明显系膜残留',
  `intraoperative_completely_tme_residual_basin_wall_tissue_loca` tinyint(3) NOT NULL DEFAULT 0 COMMENT '残留部位 1：盆前壁 2：盆左侧壁 3：盆右侧壁 4：盆底肌表面 5：骨盆出口',
  `intraoperative_pelvic_area_of_obvious_bleeding` tinyint(3) NOT NULL DEFAULT 0 COMMENT '盆腔明显出血部位 1：左nvb 2：右nvb ...',
  `intraoperative_pelvic_nerve_damage` tinyint(3) NOT NULL DEFAULT 0 COMMENT '盆神经受损 1：左nvb 2:右nvb',
  `intraoperative_hemostatic_method` tinyint(3) NOT NULL DEFAULT 0 COMMENT '止血方法 1：超声刀 2：电凝 3：缝扎 4：压迫 5：无',
  `intraoperative_operation_time_min` varchar(50) NOT NULL DEFAULT '' COMMENT '手术时间分',
  `intraoperative_length_of_the_incision` varchar(50) NOT NULL DEFAULT '' COMMENT '切口长度cm',
  `intraoperative_bleeding` varchar(50) NOT NULL DEFAULT '' COMMENT '术中出血量',
  `intraoperative_blood_transfusion` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术中输血 1:有 2：无',
  `intraoperative_blood_transfusion_reason` tinyint(3) NOT NULL DEFAULT 0 COMMENT '输血原因 1：出血 2：术前贫血',
  `intraoperative_composition_blood_transfusion` tinyint(3) NOT NULL DEFAULT 0 COMMENT '输血成分 1：血浆 2：红悬 3：全血 4：血小板',
  `intraoperative_blood_transfusion_volume` varchar(50) NOT NULL DEFAULT '' COMMENT '输血量',
  `intraoperative_intraperitoneal_chemotherapy` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术中腹腔化疗 1：无 2：有',
  `intraoperative_intraperitoneal_chemotherapy_drug_name` varchar(100) NOT NULL DEFAULT '' COMMENT '化疗药物名称',
  `intraoperative_intraperitoneal_chemotherapy_dose` varchar(100) NOT NULL DEFAULT '' COMMENT '用药剂量',
  `intraoperative_complication` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术中并发症 1：有 2：无',
  `intraoperative_complication_describe` text DEFAULT NULL COMMENT '并发症描述',
  # 肝脏手术情况
  `liver_surgery_time_choose` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肝脏手术时间 1：同时性 2：同时性(术后6月) 3：异时性',
  `liver_surgery_tran` tinyint(3) NOT NULL DEFAULT 0 COMMENT '转移情况 1：0组 2：1组 3：2 4：3',
  `liver_surgery_diagnosis_from_first` varchar(50) NOT NULL DEFAULT '' COMMENT '诊断时间距出诊月',
  `liver_surgery_diagnosis_from_first_surgery` varchar(50) NOT NULL DEFAULT '' COMMENT '距初手术月',
  `liver_surgery_diagnosis_from_neo` varchar(50) NOT NULL DEFAULT '' COMMENT '距辅助化疗月',
  `liver_surgery_treat` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肝术前治疗 1：无 2：化疗 3：射频 ...',
  `liver_surgery_gw` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肝外病灶 1：原发性 2：肠周 3：远处 4：肺 ...',
  `liver_surgery_possible` tinyint(3) NOT NULL DEFAULT 0 COMMENT '可切除性 1：可切除 2：可根治放疗 3：不可切',
  `liver_surgery_pet` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否pet 1:是 2：否',
  `liver_surgery_child` tinyint(3) NOT NULL DEFAULT 0 COMMENT '分级child 1:a 2:b 3:c',
  `liver_surgery_indole_cyanide_green_test` varchar(50) NOT NULL DEFAULT '' COMMENT '吲哚氰绿试验',
  `liver_surgery_background` tinyint(3) NOT NULL DEFAULT 0 COMMENT '1：无 2：乙肝 3：丙肝...',
  `liver_surgery_metastaticl` varchar(50) NOT NULL DEFAULT '' COMMENT '肿瘤转移瘤数',
  `liver_surgery_metastaticl_max` varchar(50) NOT NULL DEFAULT '' COMMENT '最大直径',
  `liver_surgery_metastaticl_max_and_1_cm` varchar(50) NOT NULL DEFAULT '' COMMENT '最大直径和大于等于1cm者',
  `liver_surgery_lesion` tinyint(3) NOT NULL DEFAULT 0 COMMENT '病灶部位 1：1 2：2 3：3 ...',
  `liver_surgery_resection` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肝切除 1：同期 2：分期 3：分次 4：再次 5：未手术',
  `liver_surgery_operate_type` tinyint(3) NOT NULL DEFAULT 0 COMMENT '手术方式 1：半肝切除 2：肝叶或段切除 ...',
  `liver_surgery_num_of_lesion` varchar(50) NOT NULL DEFAULT '' COMMENT '发现病灶数量',
  `liver_surgery_removal_lesion` varchar(50) NOT NULL DEFAULT '' COMMENT '切除病灶数量',
  `liver_surgery_ablation_lesion` varchar(50) NOT NULL DEFAULT '' COMMENT '消融病灶数量',
  `liver_surgery_removal_lesion_max_diameter` varchar(50) NOT NULL DEFAULT '' COMMENT '切除病灶最大直径数量',
  `liver_surgery_removal_lesion_over_cmno5` varchar(50) NOT NULL DEFAULT '' COMMENT '切除病灶直径和>=cmno5',
  `liver_surgery_missing_lesion` varchar(50) NOT NULL DEFAULT '' COMMENT '遗漏病灶数量',
  `liver_surgery_missing_lesion_location` tinyint(3) NOT NULL DEFAULT 0 COMMENT '遗漏病灶部位 1：1 2：2 3：3 4：4...',
  `liver_surgery_name` varchar(50) NOT NULL DEFAULT '' COMMENT '肝脏手术名称',
  # 术后情况
  `postoperative_anus_exhaust` varchar(50) NOT NULL DEFAULT '' COMMENT '肛门排气',
  `postoperative_pull_out_tube` varchar(50) NOT NULL DEFAULT '' COMMENT '拔除胃管',
  `postoperative_sicu` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否到sicu 1：是 2：否',
  `postoperative_sicu_observation` varchar(50) NOT NULL DEFAULT '' COMMENT 'sicu观察时间',
  `postoperative_eating_liquid` varchar(50) NOT NULL DEFAULT '' COMMENT '进食流质',
  `postoperative_eating_pap` varchar(50) NOT NULL DEFAULT '' COMMENT '进食软质',
  `postoperative_ventilator_support` tinyint(3) NOT NULL DEFAULT 0 COMMENT '呼吸机支持 1：是 2：否',
  `postoperative_ventilator_support_time_hour` varchar(50) NOT NULL DEFAULT '' COMMENT '呼吸机支持时间',
  `postoperative_oxygen_time_hour` varchar(50) NOT NULL DEFAULT '' COMMENT '吸氧时间',
  `postoperative_total_length_stay` varchar(50) NOT NULL DEFAULT '' COMMENT '总住院天数',
  `postoperative_length_stay` varchar(50) NOT NULL DEFAULT '' COMMENT '术后住院天数',
  `postoperative_complication_describe` text DEFAULT NULL COMMENT '并发症具体描述',
  `postoperative_complication` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术后并发症 1：是 2：否',
  `postoperative_complication_specific` varchar(50) NOT NULL DEFAULT '' COMMENT '1:吻合口瘘 2：腹腔出血 3：肠内出血 ...',
  `postoperative_discharge_thrombosis_score` tinyint(3) NOT NULL DEFAULT 0 COMMENT '出院时深静脉血栓评分 1：低风险小于等于10分 2：中风险11-14分 3：高风险大于等于15分',
  `postoperative_perioperative_death` tinyint(3) NOT NULL DEFAULT 0 COMMENT '围术期死亡 1：是 2：否',
  `postoperative_death_reason` text DEFAULT NULL COMMENT '死亡原因',
  `postoperative_out_hospital_complication` text DEFAULT NULL COMMENT '出院后发生并发症',
  `postoperative_surgery_again` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否再次手术 1：是 2：否',
  `postoperative_surgery_again_reason` text DEFAULT NULL COMMENT '再次手术原因',
  # 病理报告
  `pathological_report_type` tinyint(3) NOT NULL DEFAULT 0 COMMENT '病理类型 1：腺癌 2：淋巴瘤 3：间质肿瘤 4：其他肿瘤',
  `pathological_report_type_1` tinyint(3) NOT NULL DEFAULT 0 COMMENT '组织类型 1：乳头状腺癌 2：管状腺癌 ...',
  `pathological_report_tumor_size` varchar(50) NOT NULL DEFAULT '' COMMENT '病理肿瘤大小',
  `pathological_report_max_diameter` varchar(50) NOT NULL DEFAULT '' COMMENT '最大径',
  `pathological_report_tumor_deep` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肿瘤侵润深度 1：ptis 2:pt1 3:pt2 ...',
  `pathological_report_rank` tinyint(3) NOT NULL DEFAULT 0 COMMENT '分化等级 1：gx 2:g1 3:g2 4:g3 5:g4',
  `pathological_report_pt3_distance` varchar(50) NOT NULL DEFAULT '' COMMENT 'pt3肿瘤侵出肌层距离',
  `pathological_report_circumferential_cut_edge_distance` varchar(50) NOT NULL DEFAULT '' COMMENT '距环周切缘', 
  `pathological_report_new_pathology` tinyint(3) NOT NULL DEFAULT 0 COMMENT '新辅助治疗的病理疗效 1：五新辅助治疗 2：无癌细胞残留或仅有粘液',
  `pathological_report_check_ln` varchar(50) NOT NULL DEFAULT '' COMMENT '病检ln',
  `pathological_report_check_less_10_ln` varchar(50) NOT NULL DEFAULT '' COMMENT '肿瘤小于10cm检测',
  `pathological_report_check_less_10_15_ln` varchar(50) NOT NULL DEFAULT '' COMMENT '肿瘤10-15检测ln',
  `pathological_report_check_more_15_ln` varchar(50) NOT NULL DEFAULT '' COMMENT '大于15cm检测ln',
  `pathological_report_central_group_test_check_ln` varchar(50) NOT NULL DEFAULT '' COMMENT '中央组检测ln',
  `pathological_report_check_positive_ln` varchar(50) NOT NULL DEFAULT '' COMMENT '病检阳性ln',
  `pathological_report_check_positive_less_10_ln` varchar(50) NOT NULL DEFAULT '' COMMENT '肿瘤小于10cm检测',
  `pathological_report_check_positive_less_10_15_ln` varchar(50) NOT NULL DEFAULT '' COMMENT '肿瘤10-15检测ln',
  `pathological_report_check_positive_more_15_ln` varchar(50) NOT NULL DEFAULT '' COMMENT '大于15cm检测ln',
  `pathological_report_central_group_test_check_positive_ln` varchar(50) NOT NULL DEFAULT '' COMMENT '中央组检测ln',
  `pathological_report_aging_n` tinyint(3) NOT NULL DEFAULT 0 COMMENT '分期n 1：n0 2:n1a 3：n1b...',
  `pathological_report_metastatic` tinyint(3) NOT NULL DEFAULT 0 COMMENT '远处转移 1：mx 2:m0 3:m1a...',
  `pathological_report_location` text DEFAULT NULL COMMENT '具体部位',
  `pathological_report_near` tinyint(3) NOT NULL DEFAULT 0 COMMENT '近切缘 1：阴性 2：癌残留',
  `pathological_report_far` tinyint(3) NOT NULL DEFAULT 0 COMMENT '远切缘 1：阴性 2：癌残留',
  `pathological_report_invasion_lymphatics` tinyint(3) NOT NULL DEFAULT 0 COMMENT '侵袭淋巴管 1：有 2：无',
  `pathological_report_invasion_vein` tinyint(3) NOT NULL DEFAULT 0 COMMENT '侵袭静脉 1：有 2：无',
  `pathological_report_invasion_neural` tinyint(3) NOT NULL DEFAULT 0 COMMENT '侵袭神经 1：有 2：无',
  `pathological_report_paracancer_mucosal_lesion` tinyint(3) NOT NULL DEFAULT 0 COMMENT '癌旁黏膜病变 1：无腺癌 2：腺癌...',
  `pathological_report_paracancer_mesangial_integrity` tinyint(3) NOT NULL DEFAULT 0 COMMENT '癌旁系膜完整度 1：3a 2:3b 3:3c...',
  `pathological_report_miles` tinyint(3) NOT NULL DEFAULT 0 COMMENT '病理 1:差 2：标准 3：超标准 4：柱状切除',
  `pathological_report_ptnm` tinyint(3) NOT NULL DEFAULT 0 COMMENT '分期ptnm 1：0 2：1 3：2a ...',
  `pathological_report_crm` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'crm 1:阳性 2：阴性',
  `pathological_report_tumor_invade_muscular_layer` varchar(50) NOT NULL DEFAULT '' COMMENT '肿瘤侵出肌层',
  `pathological_report_tumor_cut_edge_near` varchar(50) NOT NULL DEFAULT '' COMMENT '肿瘤距切缘最近near',
  `pathological_report_pt3_tumor_involves_mesangium_deep` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'pt3肿瘤累及系膜深度 1：小于1/3 2：1/3 3：2/3 4：大于2/3',
  `pathological_report_liver_pathological_score` varchar(50) NOT NULL DEFAULT '' COMMENT '术后肝脏病理评分',
  `pathological_report_dili_pss` varchar(50) NOT NULL DEFAULT '' COMMENT 'dili-pss',
  `pathological_report_describe` text DEFAULT NULL COMMENT '具体描述',
  # 病理录入者
  `inputting_medical_records` varchar(100) NOT NULL DEFAULT '' COMMENT '病历信息录入者',
  `is_the_record_entry_complete` text DEFAULT NULL COMMENT '病历录入是否完整',
  `medical_records_information_checker` varchar(100) NOT NULL DEFAULT '' COMMENT '病历信息核查者',
  `created_at` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='直肠癌表';

DROP TABLE IF EXISTS `syy_colorectal_cancer_follow_ups`;
CREATE TABLE `syy_colorectal_cancer_follow_ups` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `colorectal_cancer_id` int(11) NOT NULL DEFAULT 0 COMMENT '直肠癌 id',
  `dead_time` int(11) NOT NULL DEFAULT 0 COMMENT '死亡日期时间(月)',
  `survival_month` varchar(100) NOT NULL DEFAULT '' COMMENT '生存月份',
  `followed_up_after_operation_date_time` int(11) NOT NULL DEFAULT 0 COMMENT '术后随访日期时间',
  `results_were_followed_up_after_operation` varchar(500) NOT NULL DEFAULT '' COMMENT '随访结局，1=无瘤生存；2=带瘤生存；3=肿瘤原因死亡；4=其他原因死亡；5=失访，原因 ',
  `long_term_complications_and_management_methods` text DEFAULT NULL COMMENT '远期并发症及处理方式',
  `whether_new_hair_gallbladder_stone` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否新发胆囊结石（0=否；1=是，2=既往合并胆囊结石）',
  `gallstone_discovery_time` int(11) NOT NULL DEFAULT 0 COMMENT '胆囊结石发现时间（年-月-日）',
  `treatment_of_gallstones` tinyint(3) NOT NULL DEFAULT 0 COMMENT '胆囊结石处理方式（1=保守，2=手术）',
  `local_recurrence_time` int(11) NOT NULL DEFAULT 0 COMMENT '局部复发时间',
  `distant_transfer_time` int(11) NOT NULL DEFAULT 0 COMMENT '远处转移时间',
  `distant_metastatic_site` varchar(300) NOT NULL DEFAULT '' COMMENT '远处转移部位（非肿瘤死亡原因）',
  `whether_chemotherapy` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否化疗 0=无；1=有；2=新辅助',
  `chemotherapy_way` tinyint(3) NOT NULL DEFAULT 0 COMMENT '化疗途径  1=口服；2=静脉',
  `chemotherapy_regimens` text DEFAULT NULL COMMENT '化疗方案',
  `chemotherapy_regimen_rate` varchar(100) NOT NULL DEFAULT '' COMMENT '化疗疗程/次',
  `chemotherapy_month` varchar(100) NOT NULL DEFAULT '' COMMENT '化疗时间（月）',
  `special_information_record` text DEFAULT NULL COMMENT '特殊信息记录',
  `follow_up_principal` varchar(100) NOT NULL DEFAULT '' COMMENT '随访负责人',
  `follow_up_note` text DEFAULT NULL COMMENT '随访备注',
  `follow_up_information_record` text DEFAULT NULL COMMENT '随访信息记录',
  `created_at` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='直肠癌随访表';

DROP TABLE IF EXISTS `syy_weight_loss`;
CREATE TABLE `syy_weight_loss` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `admin_id` int(11) NOT NULL DEFAULT 0 COMMENT '管理员id',
  `img_id` varchar(20) NOT NULL DEFAULT '' COMMENT '图片id',
  `video_id` int(11) NOT NULL DEFAULT 0 COMMENT '视频id',
  `attachment_id` varchar(20) NOT NULL DEFAULT '' COMMENT '附件id',
  `hospital_number` varchar(50) NOT NULL DEFAULT '' COMMENT '住院号',
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '姓名',
  `sex` tinyint(3) NOT NULL DEFAULT 0 COMMENT '1:男 2：女',
  `age` int(11) NOT NULL DEFAULT 0 COMMENT '年龄',
  `national` varchar(50) NOT NULL DEFAULT '' COMMENT '民族',
  `id_card` varchar(50) NOT NULL DEFAULT '' COMMENT '身份证号',
  `mobile` varchar(50) NOT NULL DEFAULT '' COMMENT '患者联系电话',
  `total_money` varchar(50) NOT NULL DEFAULT '' COMMENT '住院总费用',
  `remark` text DEFAULT NULL COMMENT '备注',
  `family_contact` varchar(100) NOT NULL DEFAULT '' COMMENT '家属联系方式',
  `admission_time` int(11) NOT NULL DEFAULT 0 COMMENT '入院日期时间',
  `operative_time` int(11) NOT NULL DEFAULT 0 COMMENT '手术日期时间',
  `discharge_time` int(11) NOT NULL DEFAULT 0 COMMENT '出院日期时间',
  `total_hospital_days` varchar(50) NOT NULL DEFAULT 0 COMMENT '总住院时间（天）',
  `postoperation_hospital_days` int(11) NOT NULL DEFAULT 0 COMMENT '术后住院时间（天）',
  `nrs2002_score` varchar(50) NOT NULL DEFAULT '' COMMENT 'nrs2002评分',
  `asa_grade` varchar(50) NOT NULL DEFAULT '' COMMENT 'asa分级',
  # 术前
  `preoperative_height` varchar(50) NOT NULL DEFAULT '' COMMENT '身高cm',
  `preoperative_weight` varchar(50) NOT NULL DEFAULT '' COMMENT '体重kg',
  `preoperative_waistline` varchar(50) NOT NULL DEFAULT '' COMMENT '腰围',
  `preoperative_bmi` varchar(50) NOT NULL DEFAULT '' COMMENT 'bmi',
  `preoperative_rbc` varchar(50) NOT NULL DEFAULT '' COMMENT 'rbc',
  `preoperative_hemoglobin` varchar(50) NOT NULL DEFAULT '' COMMENT '血红蛋白(g/l)',
  `preoperative_alanine_aminotransferase` varchar(50) NOT NULL DEFAULT '' COMMENT '谷丙转氨酶alt(u/l)',
  `preoperative_aspartate_aminotransferase` varchar(50) NOT NULL DEFAULT '' COMMENT '谷草转氨酶ast(u/l)',
  `preoperative_total_protein` varchar(50) NOT NULL DEFAULT '' COMMENT '总蛋白tp(g/l)',
  `preoperative_albumin` varchar(50) NOT NULL DEFAULT '' COMMENT '白蛋白(alb)(g/l)',
  `preoperative_prealbumin` varchar(50) NOT NULL DEFAULT '' COMMENT '前白蛋白(palb)(g/l)',
  `preoperative_trace_elements` varchar(50) NOT NULL DEFAULT '' COMMENT '微量元素',
  `preoperative_glu` varchar(50) NOT NULL DEFAULT '' COMMENT 'glu',
  `preoperative_uric_acid` varchar(50) NOT NULL DEFAULT '' COMMENT '尿酸',
  `preoperative_hdl_ch` varchar(50) NOT NULL DEFAULT '' COMMENT 'hdl-ch',
  `preoperative_tg` varchar(50) NOT NULL DEFAULT '' COMMENT 'tg',
  `preoperative_bun` varchar(50) NOT NULL DEFAULT '' COMMENT 'bun',
  `preoperative_crea` varchar(50) NOT NULL DEFAULT '' COMMENT 'crea',
  `preoperative_d_dimer` varchar(50) NOT NULL DEFAULT '' COMMENT 'd-dimer',
  `preoperative_vitb12` varchar(50) NOT NULL DEFAULT '' COMMENT 'vitb12',
  `preoperative_basal_metabolic_rate` varchar(50) NOT NULL DEFAULT '' COMMENT '基础代谢率',
  `preoperative_folic_acid` varchar(50) NOT NULL DEFAULT '' COMMENT '叶酸',
  `preoperative_renal_dysfunction` varchar(300) NOT NULL DEFAULT '' COMMENT '肾功能异常',
  `preoperative_deformation_arthritis` varchar(300) NOT NULL DEFAULT '' COMMENT '变形性关节炎',
  `preoperative_male_sexual_dysfunction` varchar(300) NOT NULL DEFAULT '' COMMENT '男性性功能异常',
  `preoperative_polycystic_ovary_syndrome` varchar(300) NOT NULL DEFAULT '' COMMENT '多囊卵巢综合征',
  `preoperative_osahs` varchar(300) NOT NULL DEFAULT '' COMMENT 'osahs',
  `preoperative_nash` varchar(300) NOT NULL DEFAULT '' COMMENT 'nash',
  `preoperative_insulin_resistance` varchar(300) NOT NULL DEFAULT '' COMMENT '胰岛素抵抗',
  `preoperative_abnormal_glucose_metabolism` varchar(300) NOT NULL DEFAULT '' COMMENT '糖代谢异常',
  `preoperative_type_2_diabetes` varchar(300) NOT NULL DEFAULT '' COMMENT '2型糖尿病',
  `preoperative_reflux_esophagitis` varchar(300) NOT NULL DEFAULT '' COMMENT '反流性食管炎',
  `preoperative_gout` varchar(300) NOT NULL DEFAULT '' COMMENT '痛风',
  `preoperative_acanthosis_nigricans` varchar(300) NOT NULL DEFAULT '' COMMENT '黑棘皮病',
  `preoperative_metabolic_syndrome` varchar(300) NOT NULL DEFAULT '' COMMENT '代谢综合征',
  # 术后第一月
  `postoperative_one_month_height` varchar(50) NOT NULL DEFAULT '' COMMENT '身高cm',
  `postoperative_one_month_weight` varchar(50) NOT NULL DEFAULT '' COMMENT '体重kg',
  `postoperative_one_month_waistline` varchar(50) NOT NULL DEFAULT '' COMMENT '腰围',
  `postoperative_one_month_bmi` varchar(50) NOT NULL DEFAULT '' COMMENT 'bmi',
  `postoperative_one_month_rbc` varchar(50) NOT NULL DEFAULT '' COMMENT 'rbc',
  `postoperative_one_month_hemoglobin` varchar(50) NOT NULL DEFAULT '' COMMENT '血红蛋白(g/l)',
  `postoperative_one_month_alanine_aminotransferase` varchar(50) NOT NULL DEFAULT '' COMMENT '谷丙转氨酶alt(u/l)',
  `postoperative_one_month_aspartate_aminotransferase` varchar(50) NOT NULL DEFAULT '' COMMENT '谷草转氨酶ast(u/l)',
  `postoperative_one_month_total_bilirubin` varchar(300) NOT NULL DEFAULT '' COMMENT '总胆红素tbil(mmol/l)',
  `postoperative_one_month_total_protein` varchar(50) NOT NULL DEFAULT '' COMMENT '总蛋白tp(g/l)',
  `postoperative_one_month_albumin` varchar(50) NOT NULL DEFAULT '' COMMENT '白蛋白(alb)(g/l)',
  `postoperative_one_month_glu` varchar(50) NOT NULL DEFAULT '' COMMENT 'glu',
  `postoperative_one_month_urea` varchar(50) NOT NULL DEFAULT '' COMMENT 'urea',
  `postoperative_one_month_crea` varchar(50) NOT NULL DEFAULT '' COMMENT 'crea',
  `postoperative_one_month_d_d_2` varchar(50) NOT NULL DEFAULT '' COMMENT 'd-d-2',
  `postoperative_one_month_basal_metabolic_rate` varchar(50) NOT NULL DEFAULT '' COMMENT '基础代谢率',
  `postoperative_one_month_folic_acid` varchar(50) NOT NULL DEFAULT '' COMMENT '叶酸',
  `postoperative_one_month_renal_dysfunction` text DEFAULT NULL COMMENT '肾功能异常',
  `postoperative_one_month_deformation_arthritis` text DEFAULT NULL COMMENT '变形性关节炎',
  `postoperative_one_month_male_sexual_dysfunction` text DEFAULT NULL COMMENT '男性性功能异常',
  `postoperative_one_month_polycystic_ovary_syndrome` text DEFAULT NULL COMMENT '多囊卵巢综合征',
  `postoperative_one_month_osahs` text DEFAULT NULL COMMENT 'osahs',
  `postoperative_one_month_nash` text DEFAULT NULL COMMENT 'nash',
  `postoperative_one_month_insulin_resistance` text DEFAULT NULL COMMENT '胰岛素抵抗',
  `postoperative_one_month_abnormal_glucose_metabolism` text DEFAULT NULL COMMENT '糖代谢异常',
  `postoperative_one_month_type_2_diabetes` text DEFAULT NULL COMMENT '2型糖尿病',
  `postoperative_one_month_reflux_esophagitis` text DEFAULT NULL COMMENT '反流性食管炎',
  `postoperative_one_month_acanthosis_nigricans` text DEFAULT NULL COMMENT '黑棘皮病',
  `postoperative_one_month_metabolic_syndrome` text DEFAULT NULL COMMENT '代谢综合征',
  `postoperative_one_month_hair_loss` text DEFAULT NULL COMMENT '脱发',
  `postoperative_one_month_diarrhea` text DEFAULT NULL COMMENT '腹泻',
  `postoperative_one_month_constipation` text DEFAULT NULL COMMENT '便秘',
  `postoperative_one_month_gallbladder_stones` text DEFAULT NULL COMMENT '胆囊结石',
  # 术后三月
  `postoperative_three_month_height` varchar(50) NOT NULL DEFAULT '' COMMENT '身高cm',
  `postoperative_three_month_weight` varchar(50) NOT NULL DEFAULT '' COMMENT '体重kg',
  `postoperative_three_month_waistline` varchar(50) NOT NULL DEFAULT '' COMMENT '腰围',
  `postoperative_three_month_bmi` varchar(50) NOT NULL DEFAULT '' COMMENT 'bmi',
  `postoperative_three_month_rbc` varchar(50) NOT NULL DEFAULT '' COMMENT 'rbc',
  `postoperative_three_month_hemoglobin` varchar(50) NOT NULL DEFAULT '' COMMENT '血红蛋白(g/l)',
  `postoperative_three_month_alanine_aminotransferase` varchar(50) NOT NULL DEFAULT '' COMMENT '谷丙转氨酶alt(u/l)',
  `postoperative_three_month_aspartate_aminotransferase` varchar(50) NOT NULL DEFAULT '' COMMENT '谷草转氨酶ast(u/l)',
  `postoperative_three_month_total_bilirubin` varchar(300) NOT NULL DEFAULT '' COMMENT '总胆红素tbil(mmol/l)',
  `postoperative_three_month_total_protein` varchar(50) NOT NULL DEFAULT '' COMMENT '总蛋白tp(g/l)',
  `postoperative_three_month_albumin` varchar(50) NOT NULL DEFAULT '' COMMENT '白蛋白(alb)(g/l)',
  `postoperative_three_month_glu` varchar(50) NOT NULL DEFAULT '' COMMENT 'glu',
  `postoperative_three_month_urea` varchar(50) NOT NULL DEFAULT '' COMMENT 'urea',
  `postoperative_three_month_crea` varchar(50) NOT NULL DEFAULT '' COMMENT 'crea',
  `postoperative_three_month_d_d_2` varchar(50) NOT NULL DEFAULT '' COMMENT 'd-d-2',
  `postoperative_three_month_basal_metabolic_rate` varchar(50) NOT NULL DEFAULT '' COMMENT '基础代谢率',
  `postoperative_three_month_folic_acid` varchar(50) NOT NULL DEFAULT '' COMMENT '叶酸',
  `postoperative_three_month_renal_dysfunction` text DEFAULT NULL COMMENT '肾功能异常',
  `postoperative_three_month_deformation_arthritis` text DEFAULT NULL COMMENT '变形性关节炎',
  `postoperative_three_month_male_sexual_dysfunction` text DEFAULT NULL COMMENT '男性性功能异常',
  `postoperative_three_month_polycystic_ovary_syndrome` text DEFAULT NULL COMMENT '多囊卵巢综合征',
  `postoperative_three_month_osahs` text DEFAULT NULL COMMENT 'osahs',
  `postoperative_three_month_nash` text DEFAULT NULL COMMENT 'nash',
  `postoperative_three_month_insulin_resistance` text DEFAULT NULL COMMENT '胰岛素抵抗',
  `postoperative_three_month_abnormal_glucose_metabolism` text DEFAULT NULL COMMENT '糖代谢异常',
  `postoperative_three_month_type_2_diabetes` text DEFAULT NULL COMMENT '2型糖尿病',
  `postoperative_three_month_acanthosis_nigricans` text DEFAULT NULL COMMENT '黑棘皮病',
  `postoperative_three_month_metabolic_syndrome` text DEFAULT NULL COMMENT '代谢综合征',
  `postoperative_three_month_reflux_esophagitis` text DEFAULT NULL COMMENT '反流性食管炎',
  `postoperative_three_month_hair_loss` text DEFAULT NULL COMMENT '脱发',
  `postoperative_three_month_diarrhea` text DEFAULT NULL COMMENT '腹泻',
  `postoperative_three_month_constipation` text DEFAULT NULL COMMENT '便秘',
  `postoperative_three_month_gallbladder_stones` text DEFAULT NULL COMMENT '胆囊结石',
  # 术后六月
  `postoperative_six_month_height` varchar(50) NOT NULL DEFAULT '' COMMENT '身高cm',
  `postoperative_six_month_weight` varchar(50) NOT NULL DEFAULT '' COMMENT '体重kg',
  `postoperative_six_month_waistline` varchar(50) NOT NULL DEFAULT '' COMMENT '腰围',
  `postoperative_six_month_bmi` varchar(50) NOT NULL DEFAULT '' COMMENT 'bmi',
  `postoperative_six_month_rbc` varchar(50) NOT NULL DEFAULT '' COMMENT 'rbc',
  `postoperative_six_month_hemoglobin` varchar(50) NOT NULL DEFAULT '' COMMENT '血红蛋白(g/l)',
  `postoperative_six_month_alanine_aminotransferase` varchar(50) NOT NULL DEFAULT '' COMMENT '谷丙转氨酶alt(u/l)',
  `postoperative_six_month_aspartate_aminotransferase` varchar(50) NOT NULL DEFAULT '' COMMENT '谷草转氨酶ast(u/l)',
  `postoperative_six_month_total_bilirubin` varchar(300) NOT NULL DEFAULT '' COMMENT '总胆红素tbil(mmol/l)',
  `postoperative_six_month_total_protein` varchar(50) NOT NULL DEFAULT '' COMMENT '总蛋白tp(g/l)',
  `postoperative_six_month_albumin` varchar(50) NOT NULL DEFAULT '' COMMENT '白蛋白(alb)(g/l)',
  `postoperative_six_month_glu` varchar(50) NOT NULL DEFAULT '' COMMENT 'glu',
  `postoperative_six_month_urea` varchar(50) NOT NULL DEFAULT '' COMMENT 'urea',
  `postoperative_six_month_crea` varchar(50) NOT NULL DEFAULT '' COMMENT 'crea',
  `postoperative_six_month_d_d_2` varchar(50) NOT NULL DEFAULT '' COMMENT 'd-d-2',
  `postoperative_six_month_basal_metabolic_rate` varchar(50) NOT NULL DEFAULT '' COMMENT '基础代谢率',
  `postoperative_six_month_folic_acid` varchar(50) NOT NULL DEFAULT '' COMMENT '叶酸',
  `postoperative_six_month_renal_dysfunction` text DEFAULT NULL COMMENT '肾功能异常',
  `postoperative_six_month_deformation_arthritis` text DEFAULT NULL COMMENT '变形性关节炎',
  `postoperative_six_month_male_sexual_dysfunction` text DEFAULT NULL COMMENT '男性性功能异常',
  `postoperative_six_month_polycystic_ovary_syndrome` text DEFAULT NULL COMMENT '多囊卵巢综合征',
  `postoperative_six_month_osahs` text DEFAULT NULL COMMENT 'osahs',
  `postoperative_six_month_nash` text DEFAULT NULL COMMENT 'nash',
  `postoperative_six_month_insulin_resistance` text DEFAULT NULL COMMENT '胰岛素抵抗',
  `postoperative_six_month_abnormal_glucose_metabolism` text DEFAULT NULL COMMENT '糖代谢异常',
  `postoperative_six_month_type_2_diabetes` text DEFAULT NULL COMMENT '2型糖尿病',
  `postoperative_six_month_acanthosis_nigricans` text DEFAULT NULL COMMENT '黑棘皮病',
  `postoperative_six_month_metabolic_syndrome` text DEFAULT NULL COMMENT '代谢综合征',
  `postoperative_six_month_reflux_esophagitis` text DEFAULT NULL COMMENT '反流性食管炎',
  `postoperative_six_month_hair_loss` text DEFAULT NULL COMMENT '脱发',
  `postoperative_six_month_diarrhea` text DEFAULT NULL COMMENT '腹泻',
  `postoperative_six_month_constipation` text DEFAULT NULL COMMENT '便秘',
  `postoperative_six_month_gallbladder_stones` text DEFAULT NULL COMMENT '胆囊结石',
  # 术后一年
  `postoperative_one_year_height` varchar(50) NOT NULL DEFAULT '' COMMENT '身高cm',
  `postoperative_one_year_weight` varchar(50) NOT NULL DEFAULT '' COMMENT '体重kg',
  `postoperative_one_year_waistline` varchar(50) NOT NULL DEFAULT '' COMMENT '腰围',
  `postoperative_one_year_bmi` varchar(50) NOT NULL DEFAULT '' COMMENT 'bmi',
  `postoperative_one_year_rbc` varchar(50) NOT NULL DEFAULT '' COMMENT 'rbc',
  `postoperative_one_year_hemoglobin` varchar(50) NOT NULL DEFAULT '' COMMENT '血红蛋白(g/l)',
  `postoperative_one_year_alanine_aminotransferase` varchar(50) NOT NULL DEFAULT '' COMMENT '谷丙转氨酶alt(u/l)',
  `postoperative_one_year_aspartate_aminotransferase` varchar(50) NOT NULL DEFAULT '' COMMENT '谷草转氨酶ast(u/l)',
  `postoperative_one_year_total_bilirubin` varchar(300) NOT NULL DEFAULT '' COMMENT '总胆红素tbil(mmol/l)',
  `postoperative_one_year_total_protein` varchar(50) NOT NULL DEFAULT '' COMMENT '总蛋白tp(g/l)',
  `postoperative_one_year_albumin` varchar(50) NOT NULL DEFAULT '' COMMENT '白蛋白(alb)(g/l)',
  `postoperative_one_year_glu` varchar(50) NOT NULL DEFAULT '' COMMENT 'glu',
  `postoperative_one_year_urea` varchar(50) NOT NULL DEFAULT '' COMMENT 'urea',
  `postoperative_one_year_crea` varchar(50) NOT NULL DEFAULT '' COMMENT 'crea',
  `postoperative_one_year_d_d_2` varchar(50) NOT NULL DEFAULT '' COMMENT 'd-d-2',
  `postoperative_one_year_basal_metabolic_rate` varchar(50) NOT NULL DEFAULT '' COMMENT '基础代谢率',
  `postoperative_one_year_folic_acid` varchar(50) NOT NULL DEFAULT '' COMMENT '叶酸',
  `postoperative_one_year_renal_dysfunction` text DEFAULT NULL COMMENT '肾功能异常',
  `postoperative_one_year_deformation_arthritis` text DEFAULT NULL COMMENT '变形性关节炎',
  `postoperative_one_year_male_sexual_dysfunction` text DEFAULT NULL COMMENT '男性性功能异常',
  `postoperative_one_year_polycystic_ovary_syndrome` text DEFAULT NULL COMMENT '多囊卵巢综合征',
  `postoperative_one_year_osahs` text DEFAULT NULL COMMENT 'osahs',
  `postoperative_one_year_nash` text DEFAULT NULL COMMENT 'nash',
  `postoperative_one_year_insulin_resistance` text DEFAULT NULL COMMENT '胰岛素抵抗',
  `postoperative_one_year_abnormal_glucose_metabolism` text DEFAULT NULL COMMENT '糖代谢异常',
  `postoperative_one_year_type_2_diabetes` text DEFAULT NULL COMMENT '2型糖尿病',
  `postoperative_one_year_acanthosis_nigricans` text DEFAULT NULL COMMENT '黑棘皮病',
  `postoperative_one_year_metabolic_syndrome` text DEFAULT NULL COMMENT '代谢综合征',
  `postoperative_one_year_reflux_esophagitis` text DEFAULT NULL COMMENT '反流性食管炎',
  `postoperative_one_year_hair_loss` text DEFAULT NULL COMMENT '脱发',
  `postoperative_one_year_diarrhea` text DEFAULT NULL COMMENT '腹泻',
  `postoperative_one_year_constipation` text DEFAULT NULL COMMENT '便秘',
  `postoperative_one_year_gallbladder_stones` text DEFAULT NULL COMMENT '胆囊结石',
  # 围术期手术
  `perioperative_complications` varchar(30) NOT NULL DEFAULT '' COMMENT '围术期手术并发症 0：无 1：胃漏...',
  `perioperative_complications_deal_way` text DEFAULT NULL COMMENT '围术期手术并发症处理方式',
  `nonoperative_complication` varchar(30) NOT NULL DEFAULT '' COMMENT '非手术并发症 0：无 1:不明原因发热...',
  `perioperative_not_complications_deal_way` text DEFAULT NULL COMMENT '围术期非手术并发症处理方式',
  `outcome` varchar(10) NOT NULL DEFAULT '' COMMENT '转归',
  # 病理录入者
  `inputting_medical_records` varchar(100) NOT NULL DEFAULT '' COMMENT '病历信息录入者',
  `is_the_record_entry_complete` text DEFAULT NULL COMMENT '病历录入是否完整',
  `medical_records_information_checker` varchar(100) NOT NULL DEFAULT '' COMMENT '病历信息核查者',
  `created_at` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='减重表';

DROP TABLE IF EXISTS `syy_weight_loss_follow_ups`;
CREATE TABLE `syy_weight_loss_follow_ups` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `weight_loss_id` int(11) NOT NULL DEFAULT 0 COMMENT '减重 id',
  `dead_time` int(11) NOT NULL DEFAULT 0 COMMENT '死亡日期时间(月)',
  `survival_month` varchar(100) NOT NULL DEFAULT '' COMMENT '生存月份',
  `followed_up_after_operation_date_time` int(11) NOT NULL DEFAULT 0 COMMENT '术后随访日期时间',
  `results_were_followed_up_after_operation` varchar(500) NOT NULL DEFAULT '' COMMENT '随访结局，1=无瘤生存；2=带瘤生存；3=肿瘤原因死亡；4=其他原因死亡；5=失访，原因 ',
  `long_term_complications_and_management_methods` text DEFAULT NULL COMMENT '远期并发症及处理方式',
  `whether_new_hair_gallbladder_stone` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否新发胆囊结石（0=否；1=是，2=既往合并胆囊结石）',
  `gallstone_discovery_time` int(11) NOT NULL DEFAULT 0 COMMENT '胆囊结石发现时间（年-月-日）',
  `treatment_of_gallstones` tinyint(3) NOT NULL DEFAULT 0 COMMENT '胆囊结石处理方式（1=保守，2=手术）',
  `local_recurrence_time` int(11) NOT NULL DEFAULT 0 COMMENT '局部复发时间',
  `distant_transfer_time` int(11) NOT NULL DEFAULT 0 COMMENT '远处转移时间',
  `distant_metastatic_site` varchar(300) NOT NULL DEFAULT '' COMMENT '远处转移部位（非肿瘤死亡原因）',
  `whether_chemotherapy` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否化疗 0=无；1=有；2=新辅助',
  `chemotherapy_way` tinyint(3) NOT NULL DEFAULT 0 COMMENT '化疗途径  1=口服；2=静脉',
  `chemotherapy_regimens` text DEFAULT NULL COMMENT '化疗方案',
  `chemotherapy_regimen_rate` varchar(100) NOT NULL DEFAULT '' COMMENT '化疗疗程/次',
  `chemotherapy_month` varchar(100) NOT NULL DEFAULT '' COMMENT '化疗时间（月）',
  `special_information_record` text DEFAULT NULL COMMENT '特殊信息记录',
  `follow_up_principal` varchar(100) NOT NULL DEFAULT '' COMMENT '随访负责人',
  `follow_up_note` text DEFAULT NULL COMMENT '随访备注',
  `follow_up_information_record` text DEFAULT NULL COMMENT '随访信息记录',
  `created_at` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='减重随访表';
