DROP TABLE IF EXISTS `syy_admins`;
CREATE TABLE `syy_admins` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT, 
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '管理员账号',
  `password` varchar(50) NOT NULL DEFAULT '' COMMENT '密码',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '管理员账号状态 0：禁用 1：开启',
  `created_at` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='管理员表';

INSERT INTO `syy_admins` VALUES (1, 'root', 'e10adc3949ba59abbe56e057f20f883e', 1, 1642750967, 1642750967);

DROP TABLE IF EXISTS `syy_menus`;
CREATE TABLE `syy_menus` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `pid` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '父级id',
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '菜单名称',
  `url` varchar(300) NOT NULL DEFAULT '' COMMENT '前端路由',
  `icon` varchar(300) NOT NULL DEFAULT '' COMMENT 'icon',
  `is_enabled` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否启用 0：不启用 1：启用',
  `sort` int(11) NOT NULL DEFAULT 0 COMMENT '排序',
  `created_at` int(20) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(20) NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='菜单表';

DROP TABLE IF EXISTS `syy_role_has_menus`;
CREATE TABLE `syy_role_has_menus` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `role_id` int(11) NOT NULL DEFAULT '0' COMMENT '角色id',
  `menu_id` int(11) NOT NULL DEFAULT '0' COMMENT '菜单id',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='角色菜单表';

DROP TABLE IF EXISTS `syy_upload_files`;
CREATE TABLE `syy_upload_files` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '文件id',
  `storage` tinyint(1) NOT NULL DEFAULT 0 COMMENT '存储方式 0：本地',
  `file_url` varchar(255) NOT NULL DEFAULT '' COMMENT '存储路径',
  `file_name` varchar(255) NOT NULL DEFAULT '' COMMENT '文件名',
  `file_size` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '文件大小(字节)',
  `file_size_m` varchar(100) NOT NULL DEFAULT '' COMMENT '文件大小(兆)',
  `file_type` varchar(200) NOT NULL DEFAULT '' COMMENT '文件类型',
  `real_name` varchar(255) NOT NULL DEFAULT '' COMMENT '文件真实名',
  `extension` varchar(20) NOT NULL DEFAULT '' COMMENT '文件扩展名',
  `created_at` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COMMENT='文件库记录表';

DROP TABLE IF EXISTS `syy_cases`;
CREATE TABLE `syy_cases` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `admin_id` int(11) NOT NULL DEFAULT 0 COMMENT '管理员id',
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '病员姓名',
  `age` int(11) NOT NULL DEFAULT 0 COMMENT '病员年龄',
  `sex` tinyint(3) NOT NULL DEFAULT 0 COMMENT '性别 0：男 1：女',
  `abstract` varchar(800) NOT NULL DEFAULT '' COMMENT '病史摘要',
  `type_id` int(11) NOT NULL DEFAULT 0 COMMENT '病例类型id',
  `part` varchar(100) NOT NULL DEFAULT '' COMMENT '部位',
  `diagnosis` varchar(300) NOT NULL DEFAULT '' COMMENT '临床诊断',
  `diagnosis_result` varchar(300) NOT NULL DEFAULT '' COMMENT '诊断结果',
  `general_seen` varchar(300) NOT NULL DEFAULT '' COMMENT '大体所见',
  `img_id` int(11) NOT NULL DEFAULT 0 COMMENT '图片id',
  `video_id` int(11) NOT NULL DEFAULT 0 COMMENT '视频id',
  `attachment_id` varchar(20) NOT NULL DEFAULT '' COMMENT '附件id',
  `status` tinyint(3) NOT NULL DEFAULT 1 COMMENT '状态 0：删除 1：正常',
  `created_at` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='病例表';

DROP TABLE IF EXISTS `syy_case_types`;
CREATE TABLE `syy_case_types` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '类型名',
  `created_at` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='病例类型表';

DROP TABLE IF EXISTS `syy_stomach_cas`;
CREATE TABLE `syy_stomach_cas` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `admin_id` int(11) NOT NULL DEFAULT 0 COMMENT '管理员id',
  `img_id` varchar(20) NOT NULL DEFAULT '' COMMENT '图片id',
  `video_id` int(11) NOT NULL DEFAULT 0 COMMENT '视频id',
  `attachment_id` varchar(20) NOT NULL DEFAULT '' COMMENT '附件id',
  `hospital_number` varchar(50) NOT NULL DEFAULT '' COMMENT '住院号',
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '姓名',
  `sex` tinyint(3) NOT NULL DEFAULT 0 COMMENT '1:男 2：女',
  `age` int(11) NOT NULL DEFAULT 0 COMMENT '年龄',
  `national` varchar(50) NOT NULL DEFAULT '' COMMENT '民族',
  `id_card` varchar(50) NOT NULL DEFAULT '' COMMENT '身份证号',
  `mobile` varchar(50) NOT NULL DEFAULT '' COMMENT '患者联系电话',
  `total_money` varchar(50) NOT NULL DEFAULT '' COMMENT '住院总费用',
  `remark` text DEFAULT NULL COMMENT '备注',
  `family_contact` varchar(100) NOT NULL DEFAULT '' COMMENT '家属联系方式',
  `preoperative_chemotherapy` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术前是否化疗 0：否 1：是',
  `preoperative_chemotherapy_laparoscopic_exploration` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术前化疗前是否腹腔镜探查 0：否 1：是',
  `laparoscopic_exploration_time` int(11) NOT NULL DEFAULT 0 COMMENT '腹腔镜探查时间',
  `laparoscopic_exploration_result` tinyint(3) NOT NULL DEFAULT 0 COMMENT '腹腔镜探查结果 1：无腹膜转移 2：有腹膜转移',
  `pci_index` varchar(100) NOT NULL DEFAULT '' COMMENT 'pci 指数',
  `laparoscopic_exploration_cast_off_result` text DEFAULT NULL COMMENT '腹腔镜探查脱落细胞结果',
  `laparoscopic_exploration_biopsy` tinyint(3) NOT NULL DEFAULT 0 COMMENT '腹腔镜探查是否取活检 0：否 1：是',
  `laparoscopic_exploration_biopsy_result` text DEFAULT NULL COMMENT '腹腔镜探查活检结果',
  `laparoscopic_exploration_prognosis` tinyint(3) NOT NULL DEFAULT 0 COMMENT '腹腔镜探查后转归 1：胃肠外科行新辅助化疗 2：肿瘤科姑息治疗',
  `preoperative_chemotherapy_scheme` text DEFAULT NULL COMMENT '术前化疗方案',
  `preoperative_chemotherapy_period` varchar(100) NOT NULL DEFAULT '' COMMENT '术前化疗周期',
  `first_period_chemotherapy_time` int(11) NOT NULL DEFAULT 0 COMMENT '第一周期化疗时间',
  `second_period_chemotherapy_time` int(11) NOT NULL DEFAULT 0 COMMENT '第二周期化疗时间',
  `third_period_chemotherapy_time` int(11) NOT NULL DEFAULT 0 COMMENT '第三周期化疗时间',
  `fourth_period_chemotherapy_time` int(11) NOT NULL DEFAULT 0 COMMENT '第四周期化疗时间',
  `chemotherapy_operative` tinyint(3) NOT NULL DEFAULT 0 COMMENT '化疗后是否手术 0：否 1：是',
  `chemotherapy_adverse_reactions` text DEFAULT NULL COMMENT '化疗期间不良反应',
  `accept_chemotherapy_clinic_evaluate` tinyint(3) NOT NULL DEFAULT 0 COMMENT '接受化疗后临床评价 1：cr 2:pr 3:sd 4:pd',
  `operative_evaluate_effect` text DEFAULT NULL COMMENT '术后病理评效',
  `admission_time` int(11) NOT NULL DEFAULT 0 COMMENT '入院日期时间',
  `operative_time` int(11) NOT NULL DEFAULT 0 COMMENT '手术日期时间',
  `discharge_time` int(11) NOT NULL DEFAULT 0 COMMENT '出院日期时间',
  `total_hospital_days` varchar(50) NOT NULL DEFAULT 0 COMMENT '总住院时间（天）',
  `postoperation_hospital_days` int(11) NOT NULL DEFAULT 0 COMMENT '术后住院时间（天）',
  `ecog_score` varchar(50) NOT NULL DEFAULT '' COMMENT 'ecog 评分',  
  `one_month_loss_of_weight` tinyint(3) NOT NULL DEFAULT 0 COMMENT '1月内体重下降 1：<=5% 2:5-10% 3:>=10%',
  `nrs2002_score` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'nrs2002评分 0: <3 1: >=3',
  `pg_sga_assessment` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'pg-sga评估 1：a 2:b 3:c',
  `nutrition_support_therapy` tinyint(3) NOT NULL DEFAULT 0 COMMENT '营养支持治疗 0：无 1：有',
  `scheme` tinyint(3) NOT NULL DEFAULT 0 COMMENT '方案：1：ten 2:pn+en 3:tpn',
  `days` varchar(100) NOT NULL DEFAULT '' COMMENT '天数（d）',
  `asa_grade` varchar(100) NOT NULL DEFAULT '' COMMENT 'asa分级',
  `main_symptoms` tinyint(3) NOT NULL DEFAULT 0 COMMENT '主要症状 0：无 1：腹痛 2：饱胀 3：呕吐 4：呕血 5：便血 6：黑便 7：吞咽困难 8：烧心感 9：厌食 10：乏力 11：体重下降 12：返酸 13：暖气 14：呃逆 15：其他',
  `main_signs` tinyint(3) NOT NULL DEFAULT 0 COMMENT '主要体征 0：无 1：腹部压痛 2：腹部包块 3：腹肌抵抗 4：胃型 5：肛检包块/结节 6：振水音 7：左锁骨上淋巴结肿大 8：移动性浊音 9：其他',
  `laparoscopic_operative_record` text DEFAULT NULL COMMENT '腹腔手术史',
  `family_record` text DEFAULT NULL COMMENT '家族史',
  `smoke` tinyint(3) NOT NULL DEFAULT 0 COMMENT '吸烟 0：无 1：有',
  `smoke_year` varchar(50) NOT NULL DEFAULT 0 COMMENT '吸烟（年）',
  `average_smoke_day` varchar(30) NOT NULL DEFAULT '' COMMENT '平均（支/天）',
  `drink` tinyint(3) NOT NULL DEFAULT 0 COMMENT '饮酒 0：无 1：有',
  `drink_year` varchar(30) NOT NULL DEFAULT '' COMMENT '饮酒年',
  `average_drink_day` varchar(30) NOT NULL DEFAULT '' COMMENT '平均（g/天）',
  `height` varchar(30) NOT NULL DEFAULT '' COMMENT '身高cm',
  `weight` varchar(30) NOT NULL DEFAULT '' COMMENT '体重kg',
  `bmi` text DEFAULT NULL COMMENT 'bmi',
  `hp` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'hp 0:阴性 1：阳性',
  `ecg` tinyint(3) NOT NULL DEFAULT 0 COMMENT '心电图 0：无特殊 1：特殊异常',
  `preoperative_lung_function` text DEFAULT NULL COMMENT '术前肺功能fev1/fvc(%)',
  `preoperative_ct` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术前ＣＴ 1＝Tx ；2＝T1a-M；T1b-SM：3＝T2-MP：4＝T3-SS；5＝T4a-SE：6＝T4b-SI：)',
  `n_aging` tinyint(3) NOT NULL DEFAULT 0 COMMENT '(Ｎ分期　1=N0/区域淋巴结无转移；　2=N1/1-2个区域淋巴结转移；3=N2/3-6个区域淋巴结转移；4=N3/7个以上区域淋巴结转移；5=Nx/区域淋巴结无法评估)',
  `preoperative_ct_check_m_aging` text DEFAULT NULL COMMENT '术前ＣＴ检查Ｍ分期　０＝  Ｍ０    1＝   Ｍ１　具 体部位)',
  `preoperative_aging` text DEFAULT NULL COMMENT '术前分期ctnm',
  `preoperative_complications_check_exception` varchar(500) NOT NULL DEFAULT '' COMMENT '术前合并症/术前检查异常',
  `preoperative_complications` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术前合并症　　１＝呼吸系统（COPD，哮喘，肺心病）；２＝循环系统（高血压，心功能不全（NYHA Ⅲ或Ⅳ)，陈旧性心肌梗塞）；３＝消化系统（肝炎，肝硬化，门脉高压，消化道溃疡，炎性肠病）；４＝内分泌（甲亢，糖尿病）；５＝泌尿系统（慢性肾炎，肾功能不全）；６＝神经系统（陈旧性脑梗塞）７＝患有其他恶性疾病：疾病名称；８＝免疫疾病后长期服用免疫抑制剂；９＝凝血机制异常或长期使用抗凝药物；１０＝其他：具体情况',
  `preoperative_chest_ct` text DEFAULT NULL COMMENT '术前胸部CT       0=正常，1=慢支，2=肺气肿，3=肺部感染，4=胸水，5=心脏长大，6=肺部占位，7=肿瘤肺部转移：具体部位',
  `ultrasound_gastroscope_tnm` text DEFAULT NULL COMMENT '超声胃镜tnm', 
  `ultrasound_imaging_tnm` text DEFAULT NULL COMMENT '超声造影tnm',
  `laparoscopic_fat_volumne` text DEFAULT NULL COMMENT '腹腔内脂肪容积',
  `napes_fat_volumne` text DEFAULT NULL COMMENT '腹壁脂肪容积',
  `her_2` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'her-2 0:阴性 1：阳性',
  `rbc` text DEFAULT NULL COMMENT 'rbc',
  `hemoglobin` varchar(100) NOT NULL DEFAULT '' COMMENT '血红蛋白（g/l）',
  `gpt` varchar(100) NOT NULL DEFAULT '' COMMENT '谷丙转氨酶alt u/l',
  `got` varchar(100) NOT NULL DEFAULT '' COMMENT '谷草转氨酶ast u/l',
  `tbil` varchar(100) NOT NULL DEFAULT '' COMMENT '总胆红素tbil mmol/l',
  `tp` varchar(100) NOT NULL DEFAULT '' COMMENT '总蛋白tp g/l',
  `alb` varchar(100) NOT NULL DEFAULT '' COMMENT '白蛋白 alb g/l',
  `palb` varchar(100) NOT NULL DEFAULT '' COMMENT '前白蛋白 palb g/l',
  `glu` text DEFAULT NULL COMMENT 'glu',
  `tg` text DEFAULT NULL COMMENT 'tg',
  `crea` text DEFAULT NULL COMMENT 'crea',
  `d_dimer` text DEFAULT NULL COMMENT 'd-dimer',
  `blood_type` tinyint(3) NOT NULL DEFAULT 0 COMMENT '血型 1：a 2:b 3:o 4:ab',
  `preoperative_afp` text DEFAULT NULL COMMENT '术前afp',
  `preoperative_cea` text DEFAULT NULL COMMENT '术前cea',
  `preoperative_ca19_9` text DEFAULT NULL COMMENT '术前ca19-9',
  `preoperative_ca125` text DEFAULT NULL COMMENT '术前ca125',
  `preoperative_ca15_3` text DEFAULT NULL COMMENT '术前ca15-3',
  `preoperative_ca72_4` text DEFAULT NULL COMMENT '术前ca72-4',
  `gas_17` text DEFAULT NULL COMMENT '胃泌素-17',
  `pepsinogen_1` text DEFAULT NULL COMMENT '胃蛋白酶原1',
  `pepsinogen_2` text DEFAULT NULL COMMENT '胃蛋白酶原2',
  `pepsinogen_1_divide_pepsinogen_2` text DEFAULT NULL COMMENT '1/2比值',
  `preoperative_ll_6` text DEFAULT NULL COMMENT '术前ll-6',
  `vitb12` text DEFAULT NULL COMMENT 'vitb12',
  `folate` text DEFAULT NULL COMMENT '叶酸',
  `evb_ca_lga` text DEFAULT NULL COMMENT 'evb-ca-lga',
  `ebv_ea_lgg` text DEFAULT NULL COMMENT 'ebv-ea-lgg',
  `pg_1_divide_pg_2` text DEFAULT NULL COMMENT 'pg-1/pg-2比值',
  `stool_ob` tinyint(3) NOT NULL DEFAULT 0 COMMENT '大便隐血 0:阴 1：阳',
  `postoperative_afp` text DEFAULT NULL COMMENT '术后afp',
  `postoperative_cea` text DEFAULT NULL COMMENT '术后cea',
  `postoperative_ca19_9` text DEFAULT NULL COMMENT '术后ca19-9',
  `postoperative_ca72_4` text DEFAULT NULL COMMENT '术后ca72-4',
  `postoperative_ca125` text DEFAULT NULL COMMENT '术后125',
  `postoperative_ca15_3` text DEFAULT NULL COMMENT '术后ca15-3',
  `postoperative_rbc` text DEFAULT NULL COMMENT '术后rbc',
  `postoperative_hemoglobin` text DEFAULT NULL COMMENT '术后血红蛋白',
  `postoperative_gpt` varchar(100) NOT NULL DEFAULT '' COMMENT '术后谷丙转氨酶alt u/l',
  `postoperative_got` varchar(100) NOT NULL DEFAULT '' COMMENT '术后谷草转氨酶ast u/l',
  `postoperative_tbil` varchar(100) NOT NULL DEFAULT '' COMMENT '术后总胆红素tbil mmol/l',
  `postoperative_tp` varchar(100) NOT NULL DEFAULT '' COMMENT '术后总蛋白tp g/l',
  `postoperative_alb` varchar(100) NOT NULL DEFAULT '' COMMENT '术后白蛋白 alb g/l',
  `postoperative_glu` varchar(100) NOT NULL DEFAULT '' COMMENT '术后glu',
  `postoperative_tg` varchar(100) NOT NULL DEFAULT '' COMMENT '术后tg',
  `postoperative_crea` varchar(100) NOT NULL DEFAULT '' COMMENT '术后crea',
  `d_d2` text DEFAULT NULL COMMENT 'd-d2',
  `amylase_in_puncture_fluid` text DEFAULT NULL COMMENT '穿刺液淀粉酶',
  `surgical_intervention` tinyint(3) NOT NULL DEFAULT 0 COMMENT '外科干预方式(0=未手术，1=根治性切除，2=姑息性切除，3=姑息性胃空肠吻合，4=探查)',
  `surgeon` varchar(100) NOT NULL DEFAULT '' COMMENT '术者',
  `road_way` tinyint(3) NOT NULL DEFAULT 0 COMMENT '入路方式（0=原位；1=拖出；2=后入路原位-3=开腹）',
  `road` tinyint(3) NOT NULL DEFAULT 0 COMMENT '入路(1=开腹，2=腹腔镜，3=胸腹联合，4=开腹+食管膈肌裂孔，5=腹腔镜+食管膈肌裂孔)',
  `laparoscopic_exploration_laparoscopy` text DEFAULT NULL COMMENT '腹腔镜探查后中转开腹原因 具体',
  `removal_way` tinyint(3) NOT NULL DEFAULT 0 COMMENT '切除方式(1=DG，2=TG，3=PG,4=局部切除)',
  `lymphadenectomy` tinyint(3) NOT NULL DEFAULT 0 COMMENT '淋巴结清扫(1=D1，2=D2，3=D2+，4=D2+PAND，5=D1+)',
  `rebuild` tinyint(3) NOT NULL DEFAULT 0 COMMENT '重建(1=Billroth-1，2=Billroth-2，3=Roux-en-Y，4=EGA，5=JPI；6=Braun)',
  `omental_sac_resection` tinyint(3) NOT NULL DEFAULT 0 COMMENT '网膜囊切除（0=未切除；1=不完全切除；2=网膜囊切除）',
  `omental_sac_resection_minutes`varchar(100) NOT NULL DEFAULT 0 COMMENT '网膜囊切除时间（分）',
  `splenic_hilar_lymph_node_clear_minutes` varchar(100) NOT NULL DEFAULT 0 COMMENT '脾门淋巴结清扫时间（分）',
  `simultaneous_organoectomy_resection` tinyint(3) NOT NULL DEFAULT 0 COMMENT '联合脏器切除(0=无，1=脾脏，2=左肝外叶，3=胰头，4=横结肠，5=胆囊，6=卵巢，7=小肠)',
  `intraoperative_organ_injury_occurred` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术中并发器官损伤(0=无，1=血管，2=脾脏，3=胰，4=横结肠，5=胆囊，6=肝脏)',
  `intraoperative_organ_injury_occurred_handle` text DEFAULT NULL COMMENT '术中并发症-出血处理',
  `intraoperative_complications_bleeding_site` text DEFAULT NULL COMMENT '术中并发症-出血部位',
  `operation_minutes` varchar(100) NOT NULL DEFAULT '' COMMENT '手术时间（分）',
  `intraoperative_blood_loss_was_estimated` varchar(100) NOT NULL DEFAULT '' COMMENT '术中估计出血量ml',
  `perioperative_blood_transfusion` tinyint(3) NOT NULL DEFAULT 0 COMMENT '围术期输血(0=未输血；1=术前；2=术中；3=术后；RBC，FFP，ALB。eg: 1-RBC 2U, 3-FFP 200ml)',
  `adverse_reactions_of_perioperative_blood_transfusion` tinyint(3) NOT NULL DEFAULT 0 COMMENT '围术期输血不良反应(0=无；1=发热；2=过敏；3=溶血；4=其它)',
  `perioperative_transfusion_unit` varchar(100) NOT NULL DEFAULT '' COMMENT '围术期输血单位',
  `chemotherapy_during_operation` varchar(100) NOT NULL DEFAULT '' COMMENT '术中化疗(0=无; 1=IOC:具体)',
  `intraoperative_carbon_nanotracers` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术中纳米碳示踪(0=否; 1=是)',
  `intraoperative_arterial_infusion_chemotherapy` text DEFAULT NULL COMMENT '术中动脉灌注化疗',
  `intraoperative_results_of_special_freezing` text DEFAULT NULL COMMENT '术中特殊冰冻结果(如网膜结节系低分化腺癌)',
  `ascites` tinyint(3) NOT NULL DEFAULT 0 COMMENT '腹水(0:无; 1:少量；2：中量；3：大量)',
  `cancer_cell` tinyint(3) NOT NULL DEFAULT 0 COMMENT ' 0=CY0:腹腔脱落癌细胞检查,未见癌细胞;     1=CY1: 找到癌细胞;    X=CYX:未做腹腔脱落癌细胞检查。',
  `peritoneal_metastasis` tinyint(3) NOT NULL DEFAULT 0 COMMENT '腹膜转移（0=P0 无腹膜扩散）；1=P1 癌灶附近腹膜，大网膜及横结肠系膜种植）；2=P2 横结肠下及膈肌腹膜少数癌灶）；3=P3 远处腹膜多数癌灶种植）；4=Px 腹膜转移无法判断）',
  `hepatic_metastases` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肝转移(0:无; 1:具体)',
  `single_hepatic_metastases` tinyint(3) NOT NULL DEFAULT 0 COMMENT '单个肝转移（１＝左叶；２＝右叶）',
  `more_hepatic_metastases` tinyint(3) NOT NULL DEFAULT 0 COMMENT '多个肝转移（１＝左叶；２＝右叶；3=左右叶均有）',
  `lymph_nodes_were_enlarged_in_16` text DEFAULT NULL COMMENT '腹膜后、肠系膜根部、16组淋巴结肿大',
  `number_of_tumor_lesions` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肿瘤病灶个数 1=单病灶；2=双病灶；3=三病灶及更多',
  `longitudinal_position_of_a_single_lesion` tinyint(3) NOT NULL DEFAULT 0 COMMENT '单病灶肿瘤纵向部位(1=胃上部U，2=胃体M，3=胃下部L，4=U+食管受累E，5=UM/MU，6=LM/ML，7=L+十二指肠受累D，8=LMU/MLU/MUL/UML)',
  `aeg` tinyint(3) NOT NULL DEFAULT 0 COMMENT '食管胃结合部腺癌  0=否，1=siewert-I型，2=siewert-II型，3=siewert-III型',
  `peridiameter_of_the_tumor` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肿瘤周径部位(1=小弯，2=大弯，3=前壁，4=后壁，5=全周)',
  `greatest_tumor_diameter` varchar(100) NOT NULL DEFAULT '' COMMENT '肿瘤最大径（如果为双病灶肿瘤描述主体病灶）(cm)',
  `intraoperative_depth_of_tumor_invasion` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术中肿瘤浸润深度 (1=原位癌，2=粘膜层，3=粘膜下层，4=浅肌层，5=深肌层，6=浆膜下层，7=浆膜层，8=临近器官受侵)',
  `cancer` tinyint(3) NOT NULL DEFAULT 0 COMMENT '(1=早癌，2=Borr-1，3=Borr-2，4=Borr-3，5=Borr-4)',
  `early_cancer_t1` tinyint(3) NOT NULL DEFAULT 0 COMMENT '早癌(T1)大体分型1=0-I 隆起型，2=0-IIa 表浅隆起型，3=0-IIb 平坦型，4=0-IIc 表浅凹陷性，5=III 凹陷型，6=混合型(按病变面积记录)', 
  `radical_degrees` tinyint(3) NOT NULL DEFAULT 0 COMMENT '根治度  1=R0；2=R1；3=R2',
  `distance_between_the_proximal_margin_and_the_tumor` varchar(100) NOT NULL DEFAULT '' COMMENT '近切缘距肿瘤距离cm',
  `distance_of_distal_margin_to_tumor` varchar(100) NOT NULL DEFAULT '' COMMENT '远切缘距肿瘤距离cm',
  `dual_foci_neoplasms_foci_1_nature` tinyint(3) NOT NULL DEFAULT 0 COMMENT '双病灶肿瘤 病灶-1：性质(1=AC=腺癌，2=GIST=间质肿瘤，3=LYM=淋巴瘤，4=NC=神经内分泌癌，5=OTHER=其它特殊类型)',
  `dual_foci_neoplasms_foci_2_nature` tinyint(3) NOT NULL DEFAULT 0 COMMENT '双病灶肿瘤 病灶-2：性质(1=AC=腺癌，2=GIST=间质肿瘤，3=LYM=淋巴瘤，4=NC=神经内分泌癌，5=OTHER=其它特殊类型)',
  `double_focal_tumor_site` tinyint(3) NOT NULL DEFAULT 0 COMMENT '双病灶肿瘤主病灶部位    1=病灶-1，    2=病灶-2',
  `bifoci_tumor_site_foci_1` tinyint(3) NOT NULL DEFAULT 0 COMMENT '双病灶肿瘤部位 病灶-1：(1=胃上部U，2=胃体M，3=胃下部L，4=U+食管受累E，5=UM/MU，6=LM/ML，7=L+十二指肠受累D，8=LMU/MLU/MUL/UML)，9=其他',
  `bifoci_tumor_site_foci_2` tinyint(3) NOT NULL DEFAULT 0 COMMENT '双病灶肿瘤部位 病灶-2：(1=胃上部U，2=胃体M，3=胃下部L，4=U+食管受累E，5=UM/MU，6=LM/ML，7=L+十二指肠受累D，8=LMU/MLU/MUL/UML)，9=其他',
  `three_or_more_lesions_and_multiple_lesions` text DEFAULT NULL COMMENT '三病灶以上多病灶肿瘤具体描述',
  `single_focal_tumor_pathology` tinyint(3) NOT NULL DEFAULT 0 COMMENT '单病灶肿瘤病理类型(1=AC=腺癌，2=GIST=间质肿瘤，3=LYM=淋巴瘤，4=NC=神经内分泌癌，5=OTHER=其它特殊类型)',
  `cell_type` tinyint(3) NOT NULL DEFAULT 0 COMMENT '细胞类型（1=乳头腺癌，2=管状腺癌，3=腺癌，4=印戒细胞癌，5=粘液细胞癌，6=类癌，7=内分泌细胞癌，8=其它，具体描述）',
  `adenocarcinoma_of_differentiation` tinyint(3) NOT NULL DEFAULT 0 COMMENT '腺癌分化程度1=Gx-无法评估；2=G1-高分化；3=G2-中分化；4=G3-低分化；5=G4-未分化；6=印戒；7=粘液腺癌',
  `lauren_type` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'lauren分型      1=肠型；2=弥漫型;3=混合型',
  `level_of_tumor` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肿瘤级别(淋巴瘤-侵袭度）1=低侵袭度；2=高侵袭度',
  `lymphoma_tnm_aging` text DEFAULT NULL COMMENT '淋巴瘤：TNM分期',
  `detection_of_frozen_cutting_edge_disease` tinyint(3) NOT NULL DEFAULT 0 COMMENT '冰冻切缘病检（0:阴性; 1：食管断端阳性；2：十二指肠断端阳性；3：胃大弯阳性；4：胃小弯阳性)',
  `resect_the_inspection_margin_again` tinyint(3) NOT NULL DEFAULT 0 COMMENT '再次切除送检切缘  0=无需再次送检，1：食管断端阴性；2：十二指肠断端阴性；3：胃大弯阴性；4：胃小弯阴性',
  `greater_omentum_margin_was_examined` tinyint(3) NOT NULL DEFAULT 0 COMMENT '大网膜边缘送检：0=阴性；1=阳性',
  `examination_of_lesser_omentum_margin` tinyint(3) NOT NULL DEFAULT 0 COMMENT '小网膜边缘送检：0=阴性；1=阳性',
  `ft_aging` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'fT分期 (1=原位癌，2=粘膜层，3=粘膜下层，4=浅肌层，5=深肌层，6=浆膜下层，7=浆膜层，8=临近器官受侵)',
  `adjacent_structures_are_infiltrated_directly` tinyint(3) NOT NULL DEFAULT 0 COMMENT '邻近结构直接浸润(0=无，1=脾脏，2=肝脏，3=胰腺，4=横结肠，5=胆囊，6=胆道，7=膈肌，8=腹后壁，9=腹前壁)',
  `fn_aging` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'fN-分期（0=N0，1=N1，2=N2,3=N3a，4=N3b，X=不详）',
  `fm_aging` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'fM分期（0=M0，1=M1）',
  `m1_aging` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'M1分期  1=淋巴结(LYM)，2=皮肤(SKI)，3=肺(PUL)，4=骨髓(MAR)，5=骨(OSS)，6=胸腔(PLE)，7=脑(BRA)，8=脑膜(MEN)，9=肾上腺(ADR)，10=后腹膜(RET)，11=卵巢(OVA)，12=肝(H), 13=腹腔脱落细胞(CY), 14=腹膜(P),15=其他(OTH)',
  `ftnm_jgca` text DEFAULT NULL COMMENT 'fTNM-JGCA',
  `ftnm` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'fTNM-(1=IA，2=IB，3=IIA，4=IIB，5=IIIA，6=IIIB，7=IIIC，8=IV，X=不详)',
  `her2` tinyint(3) NOT NULL DEFAULT 0 COMMENT 'HER2(0=0;1=1+;2=2+;3=3+;4=4+)',
  `lymphadenectomy_total` varchar(100) NOT NULL DEFAULT 0 COMMENT '淋巴结清扫总数',
  `lymph_node` varchar(100) NOT NULL DEFAULT '' COMMENT '淋巴结+', 
  `regional_lymph_nodes_cancer_nodules` varchar(100) NOT NULL DEFAULT '' COMMENT '区域淋巴结有无癌结节；0=无，1=组/个数；组/个数',
  `no1_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no.1_plus',
  `no1` varchar(100) NOT NULL DEFAULT '' COMMENT 'no1',
  `no2_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no2_plus',
  `no2` varchar(100) NOT NULL DEFAULT '' COMMENT 'no2',
  `no3_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no3_plus',
  `no3` varchar(100) NOT NULL DEFAULT '' COMMENT 'no3',
  `no3a_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no3a_plus',
  `no3a` varchar(100) NOT NULL DEFAULT '' COMMENT 'no3a',
  `no3b_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no3b_plus',
  `no3b` varchar(100) NOT NULL DEFAULT '' COMMENT 'no3b',
  `no4d_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no4d_plus',
  `no4d` varchar(100) NOT NULL DEFAULT '' COMMENT 'no4d',
  `no4sb_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no4sb_plus',
  `no4sb` varchar(100) NOT NULL DEFAULT '' COMMENT 'no4sb',
  `no4sa_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no4sa_plus',
  `no4sa` varchar(100) NOT NULL DEFAULT '' COMMENT 'no4sa',
  `no5_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no5_plus',
  `no5` varchar(100) NOT NULL DEFAULT '' COMMENT 'no5',
  `no6_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no6_plus',
  `no6` varchar(100) NOT NULL DEFAULT '' COMMENT 'no6',
  `no6a_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no6a_plus',
  `no6a` varchar(100) NOT NULL DEFAULT '' COMMENT 'no6a',
  `no6b_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no6b_plus',
  `no6b` varchar(100) NOT NULL DEFAULT '' COMMENT 'no6b',
  `no6c_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no6c_plus',
  `no6c` varchar(100) NOT NULL DEFAULT '' COMMENT 'no6c',
  `no7_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no7_plus',
  `no7` varchar(100) NOT NULL DEFAULT '' COMMENT 'no7',
  `no8a_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no8a_plus',
  `no8a` varchar(100) NOT NULL DEFAULT '' COMMENT 'no8a',
  `no8p_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no8p_plus',
  `no8p` varchar(100) NOT NULL DEFAULT '' COMMENT 'no8p',
  `no9_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no9_plus',
  `no9` varchar(100) NOT NULL DEFAULT '' COMMENT 'no9',
  `no10_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no10_plus',
  `no10` varchar(100) NOT NULL DEFAULT '' COMMENT 'no10',
  `no10p_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no10p_plus',
  `no10p` varchar(100) NOT NULL DEFAULT '' COMMENT 'no10p',
  `no11p_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no11p_plus',
  `no11p` varchar(100) NOT NULL DEFAULT '' COMMENT 'no11p',
  `no11p_back_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no11p_back_plus',
  `no11p_back` varchar(100) NOT NULL DEFAULT '' COMMENT 'no11p_back',
  `no11d_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no11d_plus',
  `no11d` varchar(100) NOT NULL DEFAULT '' COMMENT 'no11d',
  `no12a_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no12a_plus',
  `no12a` varchar(100) NOT NULL DEFAULT '' COMMENT 'no12a',
  `no12p_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no12p_plus',
  `no12p` varchar(100) NOT NULL DEFAULT '' COMMENT 'no12p',
  `no12b_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no12b_plus',
  `no12b` varchar(100) NOT NULL DEFAULT '' COMMENT 'no12b',
  `no12h_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no12h_plus',
  `no12h` varchar(100) NOT NULL DEFAULT '' COMMENT 'no12h',
  `no13_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no13_plus',
  `no13` varchar(100) NOT NULL DEFAULT '' COMMENT 'no13',
  `no14v_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no14v_plus',
  `no14v` varchar(100) NOT NULL DEFAULT '' COMMENT 'no14v',
  `no15_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no15_plus',
  `no15` varchar(100) NOT NULL DEFAULT '' COMMENT 'no15',
  `no16a1_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no16a1_plus',
  `no16a1` varchar(100) NOT NULL DEFAULT '' COMMENT 'no16a1',
  `no16a2_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no16a2_plus',
  `no16a2` varchar(100) NOT NULL DEFAULT '' COMMENT 'no16a2',
  `no16b1_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no16b1_plus',
  `no16b1` varchar(100) NOT NULL DEFAULT '' COMMENT 'no16b1',
  `no16b2_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no16b2_plus',
  `no16b2` varchar(100) NOT NULL DEFAULT '' COMMENT 'no16b2',
  `no17_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no17_plus',
  `no17` varchar(100) NOT NULL DEFAULT '' COMMENT 'no17',
  `no18_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no18_plus',
  `no18` varchar(100) NOT NULL DEFAULT '' COMMENT 'no18',
  `no19_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no19_plus',
  `no19` varchar(100) NOT NULL DEFAULT '' COMMENT 'no19',
  `no20_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no20_plus',
  `no20` varchar(100) NOT NULL DEFAULT '' COMMENT 'no20',
  `no110_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no110_plus',
  `no110` varchar(100) NOT NULL DEFAULT '' COMMENT 'no110',
  `no111_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no111_plus',
  `no111` varchar(100) NOT NULL DEFAULT '' COMMENT 'no111',
  `no112_plus` varchar(100) NOT NULL DEFAULT '' COMMENT 'no112_plus',
  `no112` varchar(100) NOT NULL DEFAULT '' COMMENT 'no112',
  `small_mesenteric_ln_plus` text DEFAULT NULL COMMENT '小肠系膜ln_plus',
  `small_mesenteric_ln` text DEFAULT NULL COMMENT '小肠系膜ln',
  `special_lymph_node` text DEFAULT NULL COMMENT '特殊淋巴结（具体描述：部位，阳性数目/清扫数目）',
  `vascular_involvement` tinyint(3) NOT NULL DEFAULT 0 COMMENT '血管受累(0=阴性；1=阳性；X=未报道)',
  `lymphatic_involvement` tinyint(3) NOT NULL DEFAULT 0 COMMENT '淋巴管受累(0=阴性；1=阳性；X=未报道)',
  `neurologic_involvement` tinyint(3) NOT NULL DEFAULT 0 COMMENT '神经受累(0=阴性；1=阳性；X=未报道)',
  `fat_examination_reveals_cancerous_nodules` tinyint(3) NOT NULL DEFAULT 0 COMMENT '脂肪查见癌结节(0=阴性；1=阳性-具体；X=未报道)',
  `vascular_tumor_emboli` tinyint(3) NOT NULL DEFAULT 0 COMMENT '脉管癌栓(0=阴性；1=阳性；X=未报道)',
  `hepatoduodenal_ligament_anterior_peritoneum` tinyint(3) NOT NULL DEFAULT 0 COMMENT '肝十二指肠韧带腹膜前叶(0=阴性；1=阳性；X=未报道)',
  `pancreas_capsule` tinyint(3) NOT NULL DEFAULT 0 COMMENT '胰腺被膜(0=阴性；1=阳性；X=未报道)',
  `anterior_lobe_of_transverse_mesentery` tinyint(3) NOT NULL DEFAULT 0 COMMENT '横结肠系膜前叶(0=阴性；1=阳性；X=未报道)',
  `stage_show` text DEFAULT NULL COMMENT '分期说明（术前MDCT，术中特殊发现，术后病理特殊信息）',
  `pathology_num` varchar(100) NOT NULL DEFAULT '' COMMENT '病理号（另自行保存病理报告副本pdf文档，以病理号命名）',
  `perioperative_nutritional_support` text DEFAULT NULL COMMENT '围术期营养支持(包括具体方案，持续时间，不良反应)',
  `perioperative_antibiotics` text DEFAULT NULL COMMENT '围术期抗生素',
  `postoperative_prophylactic_antibiotic` tinyint(3) NOT NULL DEFAULT 0 COMMENT '术后预防抗生素(1=常规用法，2=短程用法)',
  `perioperative_acid_suppressor` text DEFAULT NULL COMMENT '围术期抑酸剂',
  `perioperative_mucosal_protectant` text DEFAULT NULL COMMENT '围术期黏膜保护剂',
  `perioperative_hemostatic_agent` text DEFAULT NULL COMMENT '围术期止血药(0:无; 1:具体)',
  `perioperative_somatostatin` tinyint(3) NOT NULL DEFAULT 0 COMMENT '围术期生长抑素(0=无，1=有)',
  `perioperative_analgesics` text DEFAULT NULL COMMENT '围术期镇痛药',
  `perioperative_intensive_care` text DEFAULT NULL COMMENT '围术期重症监护',
  `other_special_treatments_during_perioperative_period` text DEFAULT NULL COMMENT '围术期其他特殊处理',
  `whether_to_install_a_gastric_tube` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否安置胃管（1，是；2，否）',
  `set_time` int(11) NOT NULL DEFAULT 0 COMMENT '安置时间（1，术前；2、术中；3，术后）',
  `extraction_date_of_gastric_tube_time` int(11) NOT NULL DEFAULT 0 COMMENT '胃管拔除日(POD)',
  `average_daily_gastric_fluid_volume` varchar(100) NOT NULL DEFAULT '' COMMENT '每日平均胃液量(ml)',
  `cause_of_gastric_tube_replacement` text DEFAULT NULL COMMENT '再次安置胃管原因：具体描述',
  `catheter_removal_time` int(11) NOT NULL DEFAULT 0 COMMENT '尿管拔除时间(POH)',
  `abdominal_drainage_tube_removal_date_time` int(11) NOT NULL DEFAULT 0 COMMENT '腹腔引流管拔除日(POD)',
  `average_daily_volume_of_abdominal_drainage_fluid` varchar(100) NOT NULL DEFAULT '' COMMENT '每日平均腹腔引流液量(ml)',
  `anal_exhaust_day_time` int(11) NOT NULL DEFAULT 0 COMMENT '肛门排气日(h)', 
  `start_an_out_of_bed_day_time` int(11) NOT NULL DEFAULT 0 COMMENT '开始下床活动日(POH)',
  `start_a_fluid_day_time` int(11) NOT NULL DEFAULT 0 COMMENT '开始进食流质日(POH)',
  `highest_temperature` varchar(100) NOT NULL DEFAULT '' COMMENT '最高体温(℃)',
  `postoperative_temperature_greater_than_38_days` varchar(100) NOT NULL DEFAULT '' COMMENT '术后体温>38℃天数(day)',
  `perioperative_complications` tinyint(3) NOT NULL DEFAULT 0 COMMENT '围术期手术并发症(0=无；1=十二指肠残端瘘，2=吻合口瘘，3=胰瘘/胰腺炎，4=肠瘘，5=胆瘘，6=淋巴乳糜瘘，7=腹腔内出血，8=消化道出血，9=麻痹性肠梗阻，10=机械性梗阻，11=胃无张力，12=切口感染/切口裂开，13=腹腔感染/腹腔脓肿/腹腔局限性积液，14=血管损伤，15=临近器官损伤，16=腹腔镜相关并发症)',
  `management_of_perioperative_complications` text DEFAULT NULL COMMENT '围术期手术并发症处理方式',
  `nonoperative_complication` text DEFAULT NULL COMMENT '非手术并发症',
  `perioperative_management_of_nonoperative_complications` text DEFAULT NULL COMMENT '围术期非手术并发症处理方式',
  `outcome` tinyint(3) NOT NULL DEFAULT 0 COMMENT '转归(1=无并发症出院，2=并发症治愈出院，3=自动出院，4=死亡)',
  `inputting_medical_records` varchar(100) NOT NULL DEFAULT '' COMMENT '病历信息录入者',
  `is_the_record_entry_complete` text DEFAULT NULL COMMENT '病历录入是否完整',
  `medical_records_information_checker` varchar(100) NOT NULL DEFAULT '' COMMENT '病历信息核查者',
  `created_at` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='胃ca表';

DROP TABLE IF EXISTS `syy_stomach_follow_ups`;
CREATE TABLE `syy_stomach_follow_ups` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `stomach_ca_id` int(11) NOT NULL DEFAULT 0 COMMENT '胃ca id',
  `dead_time` int(11) NOT NULL DEFAULT 0 COMMENT '死亡日期时间(月)',
  `survival_month` varchar(100) NOT NULL DEFAULT '' COMMENT '生存月份',
  `followed_up_after_operation_date_time` int(11) NOT NULL DEFAULT 0 COMMENT '术后随访日期时间',
  `results_were_followed_up_after_operation` varchar(500) NOT NULL DEFAULT '' COMMENT '随访结局，1=无瘤生存；2=带瘤生存；3=肿瘤原因死亡；4=其他原因死亡；5=失访，原因 ',
  `long_term_complications_and_management_methods` text DEFAULT NULL COMMENT '远期并发症及处理方式',
  `whether_new_hair_gallbladder_stone` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否新发胆囊结石（0=否；1=是，2=既往合并胆囊结石）',
  `gallstone_discovery_time` int(11) NOT NULL DEFAULT 0 COMMENT '胆囊结石发现时间（年-月-日）',
  `treatment_of_gallstones` tinyint(3) NOT NULL DEFAULT 0 COMMENT '胆囊结石处理方式（1=保守，2=手术）',
  `local_recurrence_time` int(11) NOT NULL DEFAULT 0 COMMENT '局部复发时间',
  `distant_transfer_time` int(11) NOT NULL DEFAULT 0 COMMENT '远处转移时间',
  `distant_metastatic_site` varchar(300) NOT NULL DEFAULT '' COMMENT '远处转移部位（非肿瘤死亡原因）',
  `whether_chemotherapy` tinyint(3) NOT NULL DEFAULT 0 COMMENT '是否化疗 0=无；1=有；2=新辅助',
  `chemotherapy_way` tinyint(3) NOT NULL DEFAULT 0 COMMENT '化疗途径  1=口服；2=静脉',
  `chemotherapy_regimens` text DEFAULT NULL COMMENT '化疗方案',
  `chemotherapy_regimen_rate` varchar(100) NOT NULL DEFAULT '' COMMENT '化疗疗程/次',
  `chemotherapy_month` varchar(100) NOT NULL DEFAULT '' COMMENT '化疗时间（月）',
  `special_information_record` text DEFAULT NULL COMMENT '特殊信息记录',
  `follow_up_principal` varchar(100) NOT NULL DEFAULT '' COMMENT '随访负责人',
  `follow_up_note` text DEFAULT NULL COMMENT '随访备注',
  `follow_up_information_record` text DEFAULT NULL COMMENT '随访信息记录',
  `created_at` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(11) NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='胃ca随访表';